"""Seeds de empresas grandes (B3, líderes setoriais, multinacionais BR)."""

# (nome, segmento_macro, sinais dict)
# sinais: b3, top, revenue, employees, fortune

def _b3(name, macro):
    # Listagem B3 implica porte relevante (alinha score >= 4 com critério do plano)
    return (name, macro, {"b3": True, "revenue": True})

def _top(name, macro):
    return (name, macro, {"top": True, "revenue": True})

def _both(name, macro):
    return (name, macro, {"b3": True, "top": True})

COMPANY_SEEDS = [
    # --- Financeiro (bancos, seguros, pagamentos) ---
    _b3("ABC Brasil", "Financeiro"),
    _b3("Agibank", "Financeiro"),
    _b3("Alfa Financeira", "Financeiro"),
    _b3("Asa", "Financeiro"),
    _b3("Banco ABC", "Financeiro"),
    _b3("Banco Bari", "Financeiro"),
    _b3("Banco BMG", "Financeiro"),
    _b3("Banco BMP", "Financeiro"),
    _b3("Banco BS2", "Financeiro"),
    _b3("Banco C6", "Financeiro"),
    _b3("Banco da China Brasil", "Financeiro"),
    _b3("Banco Daycoval", "Financeiro"),
    _b3("Banco Digimais", "Financeiro"),
    _b3("Banco do Nordeste", "Financeiro"),
    _b3("Banco Fibra", "Financeiro"),
    _b3("Banco Guanabara", "Financeiro"),
    _b3("Banco Industrial", "Financeiro"),
    _b3("Banco Master", "Financeiro"),
    _b3("Banco Mercantil", "Financeiro"),
    _b3("Banco Modal", "Financeiro"),
    _b3("Banco Original", "Financeiro"),
    _b3("Banco Pan", "Financeiro"),
    _b3("Banco Paulista", "Financeiro"),
    _b3("Banco Pine", "Financeiro"),
    _b3("Banco Rabobank International Brasil", "Financeiro"),
    _b3("Banco Rendimento", "Financeiro"),
    _b3("Banco Rodobens", "Financeiro"),
    _b3("Banco Santander Brasil", "Financeiro"),
    _b3("Banco Semear", "Financeiro"),
    _b3("Banco Sofisa", "Financeiro"),
    _b3("Banco Topázio", "Financeiro"),
    _b3("Banestes", "Financeiro"),
    _b3("Banrisul", "Financeiro"),
    _b3("BB Seguridade", "Financeiro"),
    _b3("Banco do Brasil", "Financeiro"),
    _b3("Bradesco", "Financeiro"),
    _b3("BRB", "Financeiro"),
    _b3("Caixa Seguridade", "Financeiro"),
    _b3("Crefisa", "Financeiro"),
    _b3("Inter", "Financeiro"),
    _b3("Itaú Unibanco", "Financeiro"),
    _b3("Nubank", "Financeiro"),
    _b3("PagSeguro", "Financeiro"),
    _b3("Paraná Banco", "Financeiro"),
    _b3("Safra", "Financeiro"),
    _b3("Santander", "Financeiro"),
    _b3("Sicoob", "Financeiro"),
    _b3("Sicredi", "Financeiro"),
    _b3("Stone", "Financeiro"),
    _b3("Unicred", "Financeiro"),
    _b3("XP Inc", "Financeiro"),
    _top("Porto Seguro", "Financeiro"),
    _top("SulAmérica", "Financeiro"),
    _top("Mapfre", "Financeiro"),
    _top("Allianz", "Financeiro"),
    _top("HDI Seguros", "Financeiro"),
    _top("Tokio Marine", "Financeiro"),
    _top("Sompo Seguros", "Financeiro"),
    _top("Zurich Brasil", "Financeiro"),
    _top("Mongeral Aegon", "Financeiro"),
    _top("Caixa Econômica Federal", "Financeiro"),
    # --- Varejo e Consumo ---
    _b3("Allos", "Varejo e Consumo"),
    _b3("Arezzo", "Varejo e Consumo"),
    _b3("Assaí", "Varejo e Consumo"),
    _b3("Atacadão", "Varejo e Consumo"),
    _b3("C&A", "Varejo e Consumo"),
    _b3("Carrefour Brasil", "Varejo e Consumo"),
    _b3("Cencosud Brasil", "Varejo e Consumo"),
    _b3("Centauro", "Varejo e Consumo"),
    _b3("Companhia Brasileira de Distribuição", "Varejo e Consumo"),
    _b3("GPA", "Varejo e Consumo"),
    _b3("Grupo Mateus", "Varejo e Consumo"),
    _b3("Grupo SBF", "Varejo e Consumo"),
    _b3("Havan", "Varejo e Consumo"),
    _b3("Lojas Americanas", "Varejo e Consumo"),
    _b3("Lojas Renner", "Varejo e Consumo"),
    _b3("Magazine Luiza", "Varejo e Consumo"),
    _b3("Marisa", "Varejo e Consumo"),
    _b3("Meliuz", "Varejo e Consumo"),
    _b3("MRV&Co", "Varejo e Consumo"),
    _b3("Multilaser", "Varejo e Consumo"),
    _b3("Natura", "Varejo e Consumo"),
    _b3("Petz", "Varejo e Consumo"),
    _b3("Pernambucanas", "Varejo e Consumo"),
    _b3("Riachuelo", "Varejo e Consumo"),
    _b3("Sendas", "Varejo e Consumo"),
    _b3("Smart Fit", "Varejo e Consumo"),
    _b3("Via", "Varejo e Consumo"),
    _b3("Vivara", "Varejo e Consumo"),
    _b3("Yduqs", "Varejo e Consumo"),
    _top("Grupo Pão de Açúcar", "Varejo e Consumo"),
    _top("O Boticário", "Varejo e Consumo"),
    _top("Grupo Soma", "Varejo e Consumo"),
    _top("Decathlon Brasil", "Varejo e Consumo"),
    _top("Zaffari", "Varejo e Consumo"),
    _top("Muffato", "Varejo e Consumo"),
    _top("Cooperativa Santa Clara", "Varejo e Consumo"),
    # --- Indústria ---
    _b3("Aeris", "Indústria"),
    _b3("Alpargatas", "Indústria"),
    _b3("Armac", "Indústria"),
    _b3("Braskem", "Indústria"),
    _b3("CSN", "Indústria"),
    _b3("Dexco", "Indústria"),
    _b3("Embraer", "Indústria"),
    _b3("Gerdau", "Indústria"),
    _b3("Grendene", "Indústria"),
    _b3("Klabin", "Indústria"),
    _b3("Marcopolo", "Indústria"),
    _b3("Metalúrgica Gerdau", "Indústria"),
    _b3("Motiva", "Indústria"),
    _b3("Nexa", "Indústria"),
    _b3("Petrobras", "Indústria"),
    _b3("Randon", "Indústria"),
    _b3("Suzano", "Indústria"),
    _b3("Tupy", "Indústria"),
    _b3("Usiminas", "Indústria"),
    _b3("Vale", "Indústria"),
    _b3("WEG", "Indústria"),
    _b3("Wilson Sons", "Indústria"),
    _b3("Yara Brasil", "Indústria"),
    _top("Tramontina", "Indústria"),
    _top("Fras-le", "Indústria"),
    _top("Schulz", "Indústria"),
    _top("WEG Equipamentos", "Indústria"),
    # --- Agro e Alimentos ---
    _b3("Ambev", "Agro e Alimentos"),
    _b3("Bauducco", "Agro e Alimentos"),
    _b3("BRF", "Agro e Alimentos"),
    _b3("Camil", "Agro e Alimentos"),
    _b3("JBS", "Agro e Alimentos"),
    _b3("Marfrig", "Agro e Alimentos"),
    _b3("Minerva", "Agro e Alimentos"),
    _b3("M Dias Branco", "Agro e Alimentos"),
    _b3("Piracanjuba", "Agro e Alimentos"),
    _b3("São Martinho", "Agro e Alimentos"),
    _b3("SLC Agrícola", "Agro e Alimentos"),
    _b3("Tereos", "Agro e Alimentos"),
    _top("Cargill Brasil", "Agro e Alimentos"),
    _top("Nestlé Brasil", "Agro e Alimentos"),
    _top("Heineken Brasil", "Agro e Alimentos"),
    _top("Coca-Cola Brasil", "Agro e Alimentos"),
    _top("PepsiCo Brasil", "Agro e Alimentos"),
    # --- Energia e Utilities ---
    _b3("AES Brasil", "Energia e Utilities"),
    _b3("Auren", "Energia e Utilities"),
    _b3("Celesc", "Energia e Utilities"),
    _b3("Cemig", "Energia e Utilities"),
    _b3("Copel", "Energia e Utilities"),
    _b3("CPFL Energia", "Energia e Utilities"),
    _b3("Eletrobras", "Energia e Utilities"),
    _b3("Eneva", "Energia e Utilities"),
    _b3("Engie Brasil", "Energia e Utilities"),
    _b3("Equatorial Energia", "Energia e Utilities"),
    _b3("Isa CTEEP", "Energia e Utilities"),
    _b3("Neoenergia", "Energia e Utilities"),
    _b3("Petrobras", "Energia e Utilities"),
    _b3("Raízen", "Energia e Utilities"),
    _b3("Sabesp", "Energia e Utilities"),
    _b3("Taesa", "Energia e Utilities"),
    _b3("Transmissão Paulista", "Energia e Utilities"),
    _b3("Ultrapar", "Energia e Utilities"),
    _b3("Vibra", "Energia e Utilities"),
    _top("Comgás", "Energia e Utilities"),
    _top("Light", "Energia e Utilities"),
    _top("Enel Brasil", "Energia e Utilities"),
    _top("EDP Brasil", "Energia e Utilities"),
    _top("BRK Ambiental", "Energia e Utilities"),
    _top("Aegea", "Energia e Utilities"),
    _top("Sanepar", "Energia e Utilities"),
    _top("Copasa", "Energia e Utilities"),
    _top("Cagece", "Energia e Utilities"),
    # --- Saúde ---
    _b3("Alliar", "Saúde"),
    _b3("Dasa", "Saúde"),
    _b3("Diagnosticos da América", "Saúde"),
    _b3("Fleury", "Saúde"),
    _b3("Hapvida", "Saúde"),
    _b3("Hypera", "Saúde"),
    _b3("Kora Saúde", "Saúde"),
    _b3("NotreDame Intermédica", "Saúde"),
    _b3("Odontoprev", "Saúde"),
    _b3("Qualicorp", "Saúde"),
    _b3("Rede D'Or", "Saúde"),
    _top("Einstein", "Saúde"),
    _top("Sírio-Libanês", "Saúde"),
    _top("Oncoclínicas", "Saúde"),
    _top("Grupo São Francisco", "Saúde"),
    _top("Prevent Senior", "Saúde"),
    # --- Tecnologia ---
    _b3("Locaweb", "Tecnologia"),
    _b3("LWSA", "Tecnologia"),
    _b3("Méliuz", "Tecnologia"),
    _b3("PagSeguro", "Tecnologia"),
    _b3("Positivo", "Tecnologia"),
    _b3("Totvs", "Tecnologia"),
    _b3("TOTVS", "Tecnologia"),
    _b3("Valid", "Tecnologia"),
    _b3("VTEX", "Tecnologia"),
    _b3("Zenvia", "Tecnologia"),
    _top("Accenture Brasil", "Tecnologia"),
    _top("Stefanini", "Tecnologia"),
    _top("CI&T", "Tecnologia"),
    _top("BRQ", "Tecnologia"),
    _top("Thoughtworks Brasil", "Tecnologia"),
    _top("Microsoft Brasil", "Tecnologia"),
    _top("Google Brasil", "Tecnologia"),
    _top("Amazon Brasil", "Tecnologia"),
    # --- Logística e Mobilidade ---
    _b3("Azul", "Logística e Mobilidade"),
    _b3("GOL", "Logística e Mobilidade"),
    _b3("JSL", "Logística e Mobilidade"),
    _b3("Localiza", "Logística e Mobilidade"),
    _b3("Movida", "Logística e Mobilidade"),
    _b3("Rumo", "Logística e Mobilidade"),
    _b3("Unidas", "Logística e Mobilidade"),
    _top("Correios", "Logística e Mobilidade"),
    _top("FedEx Brasil", "Logística e Mobilidade"),
    _top("DHL Brasil", "Logística e Mobilidade"),
    _top("iFood", "Logística e Mobilidade"),
    _top("Loggi", "Logística e Mobilidade"),
    _top("Mercado Livre", "Logística e Mobilidade"),
    # --- Construção e Imóveis ---
    _b3("Cyrela", "Construção e Imóveis"),
    _b3("Even", "Construção e Imóveis"),
    _b3("Helbor", "Construção e Imóveis"),
    _b3("JHSF", "Construção e Imóveis"),
    _b3("MRV", "Construção e Imóveis"),
    _b3("Plano&Plano", "Construção e Imóveis"),
    _b3("Tenda", "Construção e Imóveis"),
    _b3("Tecnisa", "Construção e Imóveis"),
    _top("Brookfield Brasil", "Construção e Imóveis"),
    _top("QuintoAndar", "Construção e Imóveis"),
    _top("Lavvi", "Construção e Imóveis"),
    _top("Direcional", "Construção e Imóveis"),
    _top("Trisul", "Construção e Imóveis"),
    _top("Cury", "Construção e Imóveis"),
    # --- Educação ---
    _b3("Anima", "Educação"),
    _b3("Cogna", "Educação"),
    _b3("Cruzeiro do Sul Educacional", "Educação"),
    _b3("Ser Educacional", "Educação"),
    _b3("Vasta Educação", "Educação"),
    _b3("Yduqs", "Educação"),
    _top("Estácio", "Educação"),
    _top("Kroton", "Educação"),
    _top("Grupo Salta", "Educação"),
    _top("Bernoulli", "Educação"),
    # --- Mídia e Entretenimento ---
    _b3("Globo", "Mídia e Entretenimento"),
    _b3("Telefônica Brasil", "Mídia e Entretenimento"),
    _top("Record", "Mídia e Entretenimento"),
    _top("Band", "Mídia e Entretenimento"),
    _top("UOL", "Mídia e Entretenimento"),
    _top("Spotify Brasil", "Mídia e Entretenimento"),
    # --- Serviços e Outros (infra, consultoria grande) ---
    _b3("CCR", "Serviços e Outros"),
    _b3("Ecorodovias", "Serviços e Outros"),
    _b3("EcoRodovias", "Serviços e Outros"),
    _b3("Klabin", "Serviços e Outros"),
    _top("VLI", "Serviços e Outros"),
    _top("CCR Rio", "Serviços e Outros"),
    _top("Deloitte Brasil", "Serviços e Outros"),
    _top("PwC Brasil", "Serviços e Outros"),
    _top("KPMG Brasil", "Serviços e Outros"),
    _top("EY Brasil", "Serviços e Outros"),
]
