#!/usr/bin/env python3
"""Expande known_career_urls.yaml com empresas grandes verificadas."""

import csv
import importlib.util
import re
import sys
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import requests
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from scripts.company_seeds_data import COMPANY_SEEDS
from scripts.discover_career_urls import (
    _slug_matches_url,
    candidate_urls,
    detect_platform,
    discover_one,
    load_cache,
    save_cache,
)
from scripts.expand_large_companies_br import COMPANIES as EXPAND_COMPANIES
from scripts.scoring_utils import normalize_name
from src.py.functions.df_operations import clean_url
from src.py.functions.website_verification import create_shared_session, verify_website_status

YAML_PATH = ROOT / "data/seeds/known_career_urls.yaml"
LIST_PATH = ROOT / "src/data/input/list.csv"
OUT_PATH = ROOT / "artifacts/known_career_urls_batch.yaml"
TARGET_MIN = 200
TARGET_MAX = 400

# Slugs criativos / portais conhecidos (B3, Valor 1000, Fortune BR)
CURATED_URLS: dict[str, list[str]] = {
    "Banco Daycoval": ["https://daycoval.gupy.io"],
    "Banco BV": ["https://bancobv.gupy.io", "https://carreiras.gupy.io/bv"],
    "Banco BMG": ["https://bancobmg.gupy.io", "https://carreiras.gupy.io/bmg"],
    "Banco Pan": ["https://bancopan.gupy.io", "https://carreiras.gupy.io/pan"],
    "Banco Original": ["https://original.gupy.io"],
    "Banco Sofisa": ["https://sofisa.gupy.io", "https://carreiras.gupy.io/sofisa"],
    "Banco Pine": ["https://bancopine.gupy.io"],
    "Banrisul": ["https://banrisul.gupy.io"],
    "Banco do Brasil": ["https://bb.gupy.io", "https://carreiras.gupy.io/bb"],
    "Bradesco": ["https://bradesco.gupy.io", "https://vemproitau.gupy.io"],
    "Itaú Unibanco": ["https://vemproitau.gupy.io", "https://vempra.gupy.io/itau"],
    "Santander Brasil": ["https://santander.gupy.io", "https://carreiras.gupy.io/santander"],
    "Safra": ["https://venhasersafra.gupy.io"],
    "Banco Votorantim": ["https://jobs.kenoby.com/bancobv"],
    "Votorantim": ["https://votorantimcoe.gupy.io"],
    "Votorantim Cimentos": ["https://votorantimcimentos.gupy.io"],
    "CoE Votorantim": ["https://votorantimcoe.gupy.io"],
    "Banestes": ["https://banestes.gupy.io"],
    "BRB": ["https://brb.gupy.io"],
    "PicPay": ["https://carreiras.gupy.io/picpay", "https://picpay.gupy.io"],
    "Cielo": ["https://cielo.gupy.io", "https://carreiras.gupy.io/cielo"],
    "Getnet": ["https://carreiras.gupy.io/getnet"],
    "Neon": ["https://jobs.lever.co/neon"],
    "Creditas": ["https://creditas.gupy.io"],
    "Alelo": ["https://alelo.inhire.app/vagas"],
    "Icatu Seguros": ["https://icatu.gupy.io"],
    "Tokio Marine": ["https://tokiomarine.gupy.io"],
    "Zurich Brasil": ["https://zurich.gupy.io"],
    "HDI Seguros": ["https://hdi.gupy.io"],
    "MetLife Brasil": ["https://metlife.gupy.io"],
    "Prudential do Brasil": ["https://prudential.gupy.io"],
    "Mongeral Aegon": ["https://mongeralaegon.gupy.io"],
    "Magazine Luiza": ["https://magazineluiza.inhire.app/vagas", "https://magazineluiza.gupy.io"],
    "Magalu": ["https://magazineluiza.inhire.app/vagas"],
    "Havan": ["https://carreiras.gupy.io/havan", "https://havan.gupy.io"],
    "Riachuelo": ["https://riachuelo.gupy.io"],
    "Lojas Renner": ["https://lojasrenner.gupy.io", "https://carreiras.gupy.io/renner"],
    "Centauro": ["https://centaurotalentos.gupy.io"],
    "Grupo SBF": ["https://gruposbf.gupy.io"],
    "Assaí": ["https://assai.gupy.io"],
    "Atacadão": ["https://carreiras.gupy.io/atacadao", "https://atacadao.gupy.io"],
    "Carrefour Brasil": ["https://carreiras.gupy.io/carrefour"],
    "Grupo Mateus": ["https://carreiras.gupy.io/grupomateus"],
    "Grupo Pão de Açúcar": ["https://gpabr.gupy.io", "https://paodeacucar.gupy.io"],
    "GPA": ["https://gpabr.gupy.io"],
    "Via": ["https://viavarejo.gupy.io"],
    "Via Varejo": ["https://viavarejo.gupy.io", "https://grupocasasbahia.gupy.io"],
    "Casas Bahia": ["https://grupocasasbahia.gupy.io"],
    "Americanas": ["https://americanas.gupy.io"],
    "Smart Fit": ["https://carreiras.gupy.io/smartfit"],
    "Vivara": ["https://vivara.gupy.io"],
    "Ypê": ["https://carreirasype.gupy.io"],
    "Intelbras": ["https://intelbras.gupy.io"],
    "Positivo Tecnologia": ["https://positivo.gupy.io"],
    "Multilaser": ["https://multilaser.gupy.io"],
    "Valid": ["https://valid.gupy.io"],
    "CI&T": ["https://ciandt.gupy.io", "https://ciet.gupy.io"],
    "Sinqia": ["https://jobs.quickin.io/sinqia/jobs"],
    "Alterdata": ["https://alterdata.gupy.io"],
    "Senior Sistemas": ["https://senior.gupy.io"],
    "iFood": ["https://carreiras.ifood.com.br"],
    "Mercado Livre": ["https://mercadolibre.gupy.io", "https://carreiras.gupy.io/mercadolivre"],
    "Loggi": ["https://carreiras.gupy.io/loggi"],
    "Azul": ["https://voeazul.gupy.io"],
    "GOL": ["https://gol.gupy.io"],
    "LATAM": ["https://latam.gupy.io", "https://carreiras.gupy.io/latam"],
    "CCR": ["https://ccr.gupy.io"],
    "Ecorodovias": ["https://ecorodovias.gupy.io"],
    "Arteris": ["https://arteris.gupy.io"],
    "VLI": ["https://vli-logistica.gupy.io", "https://vli.gupy.io"],
    "MRS Logística": ["https://mrslogistica.gupy.io"],
    "Hidrovias do Brasil": ["https://hidrovias.gupy.io"],
    "Santos Brasil": ["https://santosbrasil.gupy.io"],
    "Vale": ["https://vale.gupy.io", "https://carreiras.gupy.io/vale"],
    "CSN": ["https://csn.gupy.io"],
    "Braskem": ["https://braskem.gupy.io"],
    "Gerdau": ["https://career19.sapsf.com/careers?company=gerdauacos"],
    "Grendene": ["https://carreiras.gupy.io/grendene", "https://grendene.gupy.io"],
    "Tramontina": ["https://carreiras.gupy.io/tramontina", "https://tramontina.gupy.io"],
    "Marcopolo": ["https://marcopolo.gupy.io"],
    "Dexco": ["https://dexco.gupy.io"],
    "Nexa": ["https://nexa.gupy.io"],
    "Motiva": ["https://motiva.gupy.io"],
    "Yara Brasil": ["https://yara.gupy.io"],
    "MRV": ["https://carreiras.gupy.io/mrv", "https://mrv.gupy.io"],
    "Even": ["https://even.gupy.io"],
    "Helbor": ["https://helbor.gupy.io"],
    "Plano&Plano": ["https://planoeplano.gupy.io"],
    "Tecnisa": ["https://tecnisa.gupy.io"],
    "JHSF": ["https://jhsf.gupy.io"],
    "Direcional": ["https://direcional.gupy.io"],
    "Trisul": ["https://trisul.gupy.io"],
    "Lavvi": ["https://lavvi.gupy.io"],
    "Eztec": ["https://eztec.gupy.io"],
    "Gafisa": ["https://gafisa.gupy.io"],
    "Petrobras": ["https://petrobras.gupy.io", "https://carreiras.gupy.io/petrobras"],
    "Eletrobras": ["https://eletrobras.gupy.io"],
    "Cemig": ["https://cemig.gupy.io"],
    "CPFL Energia": ["https://carreiras.gupy.io/cpfl", "https://cpflenergia.gupy.io"],
    "Neoenergia": ["https://carreiras.gupy.io/neoenergia"],
    "Eneva": ["https://carreiras.gupy.io/eneva", "https://eneva.gupy.io"],
    "Engie Brasil": ["https://engie.gupy.io"],
    "Enel Brasil": ["https://enel.gupy.io"],
    "Light": ["https://light.gupy.io"],
    "Sabesp": ["https://sabesp.gupy.io"],
    "Sanepar": ["https://sanepar.gupy.io"],
    "Copasa": ["https://copasa.gupy.io"],
    "Ultrapar": ["https://carreiras.gupy.io/ultrapar"],
    "Comgás": ["https://comgas.gupy.io"],
    "Claro": ["https://claro.gupy.io", "https://carreiras.gupy.io/claro"],
    "TIM": ["https://carreiras.gupy.io/tim"],
    "Vivo": ["https://vivo.gupy.io"],
    "V.tal": ["https://vtal.gupy.io"],
    "Hapvida": ["https://hapvida.gupy.io"],
    "NotreDame Intermédica": ["https://notredame.gupy.io"],
    "Amil": ["https://career19.sapsf.com/careers?company=amilassist"],
    "Odontoprev": ["https://odontoprev.gupy.io"],
    "Hypera": ["https://hypera.gupy.io"],
    "Pague Menos": ["https://paguemenos.gupy.io"],
    "M Dias Branco": ["https://mdiasbranco.gupy.io"],
    "Bunge Brasil": ["https://bunge.gupy.io"],
    "Cargill Brasil": ["https://cargill.gupy.io"],
    "ADM": ["https://adm.gupy.io"],
    "Amaggi": ["https://carreiras.gupy.io/amaggi"],
    "SLC Agrícola": ["https://slcagricola.gupy.io"],
    "São Martinho": ["https://saomartinho.gupy.io"],
    "Copersucar": ["https://copersucar.gupy.io"],
    "Raízen": ["https://genteraizen.gupy.io"],
    "Yakult Brasil": ["https://yakult.gupy.io"],
    "Nestlé Brasil": ["https://nestle.gupy.io"],
    "Danone Brasil": ["https://danone.gupy.io"],
    "Mondelez Brasil": ["https://mondelez.gupy.io"],
    "PepsiCo Brasil": ["https://pepsico.gupy.io"],
    "Coca-Cola Brasil": ["https://cocacola.gupy.io"],
    "Cogna": ["https://cogna.gupy.io"],
    "Anima": ["https://anima.gupy.io"],
    "Cruzeiro do Sul Educacional": ["https://cruzeirodosul.gupy.io"],
    "Ser Educacional": ["https://sereducacional.gupy.io"],
    "Afya": ["https://afya.gupy.io"],
    "Estácio": ["https://estacio.gupy.io"],
    "Kroton": ["https://kroton.gupy.io"],
    "Alura": ["https://alun.inhire.app/alura/vagas"],
    "SBT": ["https://sbt.gupy.io"],
    "CNN Brasil": ["https://cnnbrasil.gupy.io"],
    "Jovem Pan": ["https://jovempan.gupy.io"],
    "Accenture": ["https://www.accenture.com/br-pt/careers"],
    "Deloitte": ["https://jobs.deloitte.com.br"],
    "KPMG": ["https://careers.kpmg.com.br"],
    "PwC": ["https://www.pwc.com.br/pt/carreira-na-pwc.html"],
    "EY": ["https://careers.ey.com"],
    "Atento": ["https://atento.gupy.io"],
    "Teleperformance": ["https://teleperformance.gupy.io"],
    "Adecco": ["https://adecco.gupy.io"],
    "McDonald's": ["https://trabalheconosconamc.infojobs.com.br"],
    "Arcos Dorados": ["https://trabalheconosconamc.infojobs.com.br"],
    "Burger King": ["https://burgerking.gupy.io"],
    "Starbucks": ["https://starbucks.gupy.io"],
    "Cacau Show": ["https://cacaushow.gupy.io"],
    "Sodexo": ["https://pluxee.gupy.io"],
    "Andrade Gutierrez": ["https://andradegutierrez.gupy.io"],
    "Camargo Corrêa": ["https://camargocorrea.gupy.io"],
    "Ambipar": ["https://carreiras.gupy.io/ambipar"],
    "Iguatemi": ["https://iguatemi.gupy.io"],
    "Multiplan": ["https://multiplan.gupy.io"],
    "BrMalls": ["https://brmalls.gupy.io"],
    "B3": ["https://carreiras.gupy.io/b3"],
    "Wilson Sons": ["https://wilsonsons.gupy.io"],
    "Aeris": ["https://aeris.gupy.io"],
    "Armac": ["https://armac.gupy.io"],
    "Fras-le": ["https://frasle.gupy.io"],
    "Schulz": ["https://schulz.gupy.io"],
    "Iochpe-Maxion": ["https://maxion.gupy.io"],
    "Scania": ["https://scania.gupy.io"],
    "Mercedes-Benz Brasil": ["https://mercedesbenz.gupy.io"],
    "Hyundai Brasil": ["https://hyundai.gupy.io"],
    "Renault Brasil": ["https://renault.gupy.io"],
    "Nissan Brasil": ["https://nissan.gupy.io"],
    "BMW Brasil": ["https://bmw.gupy.io"],
    "Pirelli Brasil": ["https://pirelli.gupy.io"],
    "Michelin": ["https://michelin.gupy.io"],
    "Bridgestone Brasil": ["https://bridgestone.gupy.io"],
    "Goodyear Brasil": ["https://goodyear.gupy.io"],
    "Bayer Brasil": ["https://bayer.gupy.io"],
    "BASF Brasil": ["https://basf.gupy.io"],
    "Dow Brasil": ["https://dow.gupy.io"],
    "Syngenta Brasil": ["https://syngenta.gupy.io"],
    "Corteva Agriscience": ["https://corteva.gupy.io"],
    "John Deere": ["https://johndeere.gupy.io"],
    "CNH Industrial": ["https://cnhindustrial.gupy.io"],
    "Agrale": ["https://agrale.gupy.io"],
    "Jacto": ["https://jacto.gupy.io"],
    "Kepler Weber": ["https://keplerweber.gupy.io"],
    "3R Petroleum": ["https://3rpetroleum.gupy.io"],
    "PetroRio": ["https://petrorio.gupy.io"],
    "PRIO": ["https://prio.gupy.io"],
    "Taesa": ["https://taesa.gupy.io"],
    "Isa CTEEP": ["https://cteep.gupy.io"],
    "Transmissão Paulista": ["https://transmissaopaulista.gupy.io"],
    "Auren": ["https://auren.gupy.io"],
    "Omega Energia": ["https://omegaenergia.gupy.io"],
    "Casa dos Ventos": ["https://casadosventos.gupy.io"],
    "Renova Energia": ["https://renovaenergia.gupy.io"],
    "Alupar": ["https://alupar.gupy.io"],
    "Energisa": ["https://energisa.gupy.io"],
    "CVC": ["https://cvc.gupy.io"],
    "Localiza": ["https://localiza.gupy.io"],
    "Simpar": ["https://simpar.gupy.io"],
    "Vamos": ["https://vamos.gupy.io"],
    "Tegma": ["https://tegma.gupy.io"],
    "Jadlog": ["https://jadlog.gupy.io"],
    "DHL Brasil": ["https://dhl.gupy.io"],
    "FedEx Brasil": ["https://fedex.gupy.io"],
    "UPS Brasil": ["https://ups.gupy.io"],
    "Kuehne Nagel": ["https://kuehne-nagel.gupy.io"],
    "DB Schenker": ["https://dbschenker.gupy.io"],
    "Roche Brasil": ["https://roche.gupy.io"],
    "Pfizer Brasil": ["https://pfizer.gupy.io"],
    "Novartis Brasil": ["https://novartis.gupy.io"],
    "Sanofi Brasil": ["https://sanofi.gupy.io"],
    "AstraZeneca Brasil": ["https://astrazeneca.gupy.io"],
    "Abbott Brasil": ["https://abbott.gupy.io"],
    "Bristol Myers Squibb": ["https://bms.gupy.io"],
    "Boehringer Ingelheim": ["https://boehringeringelheim.gupy.io"],
    "Takeda Brasil": ["https://takeda.gupy.io"],
    "Novo Nordisk": ["https://novonordisk.gupy.io"],
    "Libbs": ["https://libbs.gupy.io"],
    "Cristália": ["https://cristalia.gupy.io"],
    "União Química": ["https://uniaoquimica.gupy.io"],
    "Prati Donaduzzi": ["https://pratidonaduzzi.gupy.io"],
    "Panvel": ["https://panvel.gupy.io"],
    "Drogaria Araujo": ["https://araujo.gupy.io"],
    "Profarma": ["https://profarma.gupy.io"],
    "Mater Dei": ["https://materdei.gupy.io"],
    "Hospital Sírio-Libanês": ["https://siriolibanes.gupy.io"],
    "Oncoclínicas": ["https://oncoclinicas.gupy.io"],
    "Qualicorp": ["https://qualicorp.gupy.io"],
    "Kora Saúde": ["https://korasaude.gupy.io"],
    "Alliar": ["https://carreiras.gupy.io/alliar"],
    "Hermes Pardini": ["https://hermespardini.gupy.io"],
    "Unimed Brasil": ["https://unimed.gupy.io"],
    "Brookfield Brasil": ["https://brookfield.gupy.io"],
    "Cushman & Wakefield": ["https://cushmanwakefield.gupy.io"],
    "CBRE": ["https://cbre.gupy.io"],
    "JLL": ["https://jll.gupy.io"],
    "Lopes Imóveis": ["https://lopes.gupy.io"],
    "Metrô São Paulo": ["https://metrosp.gupy.io"],
    "CPTM": ["https://cptm.gupy.io"],
    "Infraero": ["https://infraero.gupy.io"],
    "GRU Airport": ["https://gruairport.gupy.io"],
    "Cinemark": ["https://cinemark.gupy.io"],
    "Cinépolis": ["https://cinepolis.gupy.io"],
    "Time For Fun": ["https://t4f.gupy.io"],
    "T4F": ["https://t4f.gupy.io"],
    "Netflix Brasil": ["https://jobs.netflix.com"],
    "Spotify Brasil": ["https://www.lifeatspotify.com/jobs"],
    "Disney Brasil": ["https://jobs.disneycareers.com"],
    "Electronic Arts": ["https://ea.gr8people.com"],
    "Riot Games Brasil": ["https://riotgames.com/careers"],
    "Apple Brasil": ["https://www.apple.com/careers/br"],
    "Microsoft Brasil": ["https://careers.microsoft.com"],
    "Google Brasil": ["https://careers.google.com"],
    "Amazon Brasil": ["https://www.amazon.jobs"],
    "Oracle Brasil": ["https://oracle.taleo.net/careersection"],
    "SAP Brasil": ["https://jobs.sap.com"],
    "IBM Brasil": ["https://www.ibm.com/careers"],
    "Dell Brasil": ["https://jobs.dell.com"],
    "Cisco Brasil": ["https://jobs.cisco.com"],
    "Intel Brasil": ["https://jobs.intel.com"],
    "Lenovo": ["https://jobs.lenovo.com"],
    "Salesforce": ["https://careers.salesforce.com"],
    "Adobe": ["https://adobe.wd5.myworkdayjobs.com/external_experienced"],
    "Stripe": ["https://stripe.com/jobs"],
    "Shopify": ["https://www.shopify.com/careers"],
    "HubSpot": ["https://www.hubspot.com/careers"],
    "Zendesk": ["https://zendesk.wd1.myworkdayjobs.com"],
    "Twilio": ["https://jobs.twilio.com"],
    "GitLab": ["https://about.gitlab.com/jobs"],
    "MongoDB": ["https://www.mongodb.com/careers"],
    "Snowflake": ["https://careers.snowflake.com"],
    "Datadog": ["https://careers.datadoghq.com"],
    "Cloudflare": ["https://www.cloudflare.com/careers"],
    "Palo Alto Networks": ["https://jobs.paloaltonetworks.com"],
    "Fortinet": ["https://www.fortinet.com/corporate/careers"],
    "CrowdStrike": ["https://crowdstrike.wd5.myworkdayjobs.com"],
    "VMware": ["https://careers.vmware.com"],
    "Red Hat": ["https://redhat.wd5.myworkdayjobs.com"],
    "Capgemini": ["https://www.capgemini.com/careers"],
    "Cognizant": ["https://careers.cognizant.com"],
    "Wipro": ["https://careers.wipro.com"],
    "Infosys": ["https://www.infosys.com/careers"],
    "Tata Consultancy Services": ["https://www.tcs.com/careers"],
    "ThoughtWorks": ["https://www.thoughtworks.com/careers"],
    "Globant": ["https://careers.globant.com"],
    "EPAM": ["https://www.epam.com/careers"],
    "DXC Technology": ["https://careers.dxc.com"],
    "Atos": ["https://atos.net/en/careers"],
    "Unisys": ["https://www.unisys.com/careers"],
    "Indra Brasil": ["https://www.indracompany.com/careers"],
    "Sonda Brasil": ["https://sonda.gupy.io"],
    "Politec": ["https://politec.gupy.io"],
    "Compass UOL": ["https://compassuol.gupy.io"],
    "Serasa Experian": ["https://serasa.gupy.io"],
    "ClearSale": ["https://clearsale.gupy.io"],
    "Idwall": ["https://idwall.gupy.io"],
    "Unico": ["https://unico.gupy.io"],
    "ClickSign": ["https://clicksign.gupy.io"],
    "Sankhya": ["https://sankhya.gupy.io"],
    "Omie": ["https://omie.gupy.io"],
    "Conta Azul": ["https://contaazul.gupy.io"],
    "Bling": ["https://bling.gupy.io"],
    "Hotmart": ["https://hotmart.gupy.io"],
    "Eduzz": ["https://eduzz.gupy.io"],
    "Olist": ["https://olist.gupy.io"],
    "MadeiraMadeira": ["https://madeiramadeira.gupy.io"],
    "Mobly": ["https://mobly.gupy.io"],
    "Dafiti": ["https://dafiti.gupy.io"],
    "Original": ["https://original.gupy.io"],
    "Wiz": ["https://wiz.gupy.io"],
    "Netshoes": ["https://jobs.kenoby.com/gruponetshoes"],
    "Kabum": ["https://99jobs.com/kabum/jobs"],
    "KaBuM": ["https://99jobs.com/kabum/jobs"],
    "Fast Shop": ["https://fastshop.gupy.io"],
    "Colombo": ["https://colombo.gupy.io"],
    "Polishop": ["https://polishop.gupy.io"],
    "Reserva": ["https://reserva.gupy.io", "https://usereserva.gupy.io"],
    "Osklen": ["https://osklen.gupy.io"],
    "Animale": ["https://animale.gupy.io"],
    "Farm Rio": ["https://farmrio.gupy.io"],
    "Schutz": ["https://schutz.gupy.io"],
    "Arezzo&Co": ["https://azzas2154.gupy.io"],
    "Malwee": ["https://malwee.gupy.io"],
    "Lupo": ["https://lupo.gupy.io"],
    "Melissa": ["https://melissa.gupy.io"],
    "Olympikus": ["https://olympikus.gupy.io"],
    "Vulcabras": ["https://vulcabras.gupy.io"],
    "Eudora": ["https://eudora.gupy.io"],
    "Granado": ["https://granado.gupy.io"],
    "L'Oréal Brasil": ["https://loreal.gupy.io"],
    "Unilever Brasil": ["https://unilever.gupy.io"],
    "P&G": ["https://pg.gupy.io"],
    "Johnson & Johnson": ["https://jnj.gupy.io"],
    "Colgate": ["https://colgate.gupy.io"],
    "Henkel": ["https://henkel.gupy.io"],
    "Bombril": ["https://bombril.gupy.io"],
    "Grupo Petrópolis": ["https://petropolis.gupy.io"],
    "Heineken Brasil": ["https://heineken.gupy.io"],
    "Diageo Brasil": ["https://diageo.gupy.io"],
    "Pernod Ricard Brasil": ["https://pernodricard.gupy.io"],
    "Lactalis Brasil": ["https://lactalis.gupy.io"],
    "Vigor": ["https://vigor.gupy.io"],
    "Itambé": ["https://itambe.gupy.io"],
    "Tirol Laticínios": ["https://tirol.gupy.io"],
    "Copacol": ["https://copacol.gupy.io"],
    "Aurora Alimentos": ["https://aurora.gupy.io"],
    "Frimesa": ["https://frimesa.gupy.io"],
    "Seara": ["https://seara.gupy.io"],
    "BR Foods": ["https://brfoods.gupy.io"],
    "Tereos": ["https://tereos.gupy.io"],
    "Jalles Machado": ["https://jallesmachado.gupy.io"],
    "Atvos": ["https://atvos.gupy.io"],
    "Caramuru Alimentos": ["https://caramuru.gupy.io"],
    "Granol": ["https://granol.gupy.io"],
    "BrasilAgro": ["https://brasilagro.gupy.io"],
    "Vittia": ["https://vittia.gupy.io"],
    "3Tentos": ["https://3tentos.gupy.io"],
    "Boa Safra Sementes": ["https://boasafra.gupy.io"],
    "Mosaic Fertilizantes": ["https://mosaic.gupy.io"],
    "Heringer": ["https://heringer.gupy.io"],
    "Fertipar": ["https://fertipar.gupy.io"],
    "Ouro Fino Saúde Animal": ["https://ourofino.gupy.io"],
    "Vetnil": ["https://vetnil.gupy.io"],
    "Mantecorp": ["https://mantecorp.gupy.io"],
    "Biolab": ["https://biolab.gupy.io"],
    "Apsen": ["https://apsen.gupy.io"],
    "Cimed": ["https://cimed.gupy.io"],
    "Geolab": ["https://geolab.gupy.io"],
    "Sandoz": ["https://sandoz.gupy.io"],
    "Brainfarma": ["https://brainfarma.gupy.io"],
    "Cellera Farma": ["https://cellera.gupy.io"],
    "Galena": ["https://galena.gupy.io"],
    "Memed": ["https://memed.gupy.io"],
    "MV Sistemas": ["https://mvsistemas.gupy.io"],
    "Pixeon": ["https://pixeon.gupy.io"],
    "Zenklub": ["https://zenklub.gupy.io"],
    "FGV": ["https://fgv.gupy.io"],
    "Insper": ["https://insper.gupy.io"],
    "Ibmec": ["https://ibmec.gupy.io"],
    "ESPM": ["https://espm.gupy.io"],
    "Descomplica": ["https://descomplica.gupy.io"],
    "Trybe": ["https://trybe.gupy.io"],
    "Rocketseat": ["https://rocketseat.gupy.io"],
    "Wizard": ["https://wizard.gupy.io"],
    "Wise Up": ["https://wiseup.gupy.io"],
    "CCAA": ["https://ccaa.gupy.io"],
    "Fisk": ["https://fisk.gupy.io"],
    "Kumon": ["https://kumon.gupy.io"],
    "Maple Bear": ["https://maplebear.gupy.io"],
    "Bernoulli": ["https://bernoulli.gupy.io"],
    "Poliedro": ["https://poliedro.gupy.io"],
    "Eleva Educação": ["https://eleva.gupy.io"],
    "Vasta Educação": ["https://vasta.gupy.io"],
    "Unicesumar": ["https://unicesumar.gupy.io"],
    "Vitru": ["https://vitru.gupy.io"],
    "Anhanguera": ["https://anhanguera.gupy.io"],
    "Unopar": ["https://unopar.gupy.io"],
    "Pearson Brasil": ["https://pearson.gupy.io"],
    "Elsevier": ["https://elsevier.gupy.io"],
    "McKinsey & Company": ["https://www.mckinsey.com/careers"],
    "BCG": ["https://careers.bcg.com"],
    "Bain & Company": ["https://www.bain.com/careers"],
    "Aon": ["https://aon.teamtailor.com"],
    "Marsh": ["https://marshmclennan.wd1.myworkdayjobs.com"],
    "Mercer": ["https://careers.mercer.com"],
    "ManpowerGroup": ["https://www.manpowergroup.com/careers"],
    "Randstad Brasil": ["https://www.randstad.com.br"],
    "Robert Half": ["https://www.roberthalf.com.br"],
    "ISS Brasil": ["https://iss.gupy.io"],
    "Manserv": ["https://manserv.gupy.io"],
    "GPS Group": ["https://gps.gupy.io"],
    "Tahto": ["https://tahto.gupy.io"],
    "Liq Corp": ["https://liq.gupy.io"],
    "Verzani & Sandrini": ["https://verzani.gupy.io"],
    "Gympass": ["https://gympass.gupy.io"],
    "Wellhub": ["https://gympass.gupy.io"],
    "Caju": ["https://caju.gupy.io"],
    "Flash": ["https://flash.gupy.io"],
    "Swile": ["https://swile.gupy.io"],
    "Ticket": ["https://carreiras.gupy.io/edenred"],
    "Edenred": ["https://pluxee.gupy.io"],
    "Sem Parar": ["https://semparar.gupy.io"],
    "Livelo": ["https://carreiras.gupy.io/livelo"],
    "Enjoei": ["https://carreiras.gupy.io/enjoei"],
    "AgroGalaxy": ["https://carreiras.gupy.io/agrogalaxy"],
    "Multilog": ["https://carreiras.gupy.io/multilog"],
    "KMM": ["https://carreiras.gupy.io/kmm"],
    "Warren": ["https://carreiras.gupy.io/warren"],
    "Genial Investimentos": ["https://genial.gupy.io"],
    "Toro Investimentos": ["https://toroinvestimentos.gupy.io"],
    "Órama": ["https://orama.gupy.io"],
    "Rico": ["https://rico.gupy.io"],
    "Clear": ["https://clear.gupy.io"],
    "Vinci Partners": ["https://vincipartners.gupy.io"],
    "Pátria Investimentos": ["https://patria.gupy.io"],
    "Kinea": ["https://kinea.gupy.io"],
    "IRB Brasil RE": ["https://irbbrasil.gupy.io"],
    "Wiz": ["https://wiz.gupy.io"],
    "Banco do Nordeste": ["https://bndes.gupy.io"],
    "BNDES": ["https://bndes.gupy.io"],
    "Caixa Econômica Federal": ["https://caixa.gupy.io"],
    "Banco da Amazônia": ["https://basa.gupy.io"],
    "Banese": ["https://banese.gupy.io"],
    "Banpará": ["https://banpara.gupy.io"],
    "Banco Mercantil do Brasil": ["https://mercantil.gupy.io"],
    "Banco ABC Brasil": ["https://abcbrasil.gupy.io"],
    "Banco Industrial": ["https://bancoindustrial.gupy.io"],
    "Banco Topázio": ["https://topazio.gupy.io"],
    "Banco Master": ["https://master.gupy.io"],
    "Banco Semear": ["https://semear.gupy.io"],
    "Paraná Banco": ["https://paranabanco.gupy.io"],
    "Banco Rendimento": ["https://rendimento.gupy.io"],
    "Banco Rodobens": ["https://rodobens.gupy.io"],
    "Banco Guanabara": ["https://guanabara.gupy.io"],
    "Banco Fibra": ["https://fibra.gupy.io"],
    "Banco Bari": ["https://bari.gupy.io"],
    "Banco BMP": ["https://bmp.gupy.io"],
    "Banco Digimais": ["https://digimais.gupy.io"],
    "Asaas": ["https://asaas.gupy.io"],
    "Cora": ["https://cora.gupy.io"],
    "Conta Simples": ["https://contasimples.gupy.io"],
    "Dock": ["https://dock.gupy.io"],
    "Pismo": ["https://pismo.gupy.io"],
    "Zoop": ["https://zoop.gupy.io"],
    "Ebanx": ["https://ebanx.gupy.io"],
    "Adyen": ["https://careers.adyen.com"],
    "SumUp Brasil": ["https://sumup.gupy.io"],
    "Vindi": ["https://vindi.gupy.io"],
    "Iugu": ["https://iugu.gupy.io"],
    "Pagar.me": ["https://pagarme.gupy.io"],
    "Contabilizei": ["https://contabilizei.gupy.io"],
    "BHub": ["https://bhub.gupy.io"],
    "Open Co": ["https://openc.gupy.io"],
    "Méliuz": ["https://meliuz.gupy.io"],
    "99": ["https://carreiras.gupy.io/99"],
    "Uber": ["https://www.uber.com/careers"],
    "Rappi": ["https://rappi.gupy.io"],
    "Buser": ["https://buser.gupy.io"],
    "FlixBus": ["https://flixbus.gupy.io"],
    "Airbus Brasil": ["https://airbus.gupy.io"],
    "Boeing Brasil": ["https://boeing.wd1.myworkdayjobs.com"],
    "AENA Brasil": ["https://aena.gupy.io"],
    "ANAC": ["https://anac.gupy.io"],
    "Geodis": ["https://geodis.gupy.io"],
    "Mainfreight": ["https://mainfreight.gupy.io"],
    "CEVA Logistics": ["https://cevalogistics.gupy.io"],
    "XPO Logistics": ["https://xpo.gupy.io"],
    "GLP Brasil": ["https://glp.gupy.io"],
    "Prologis": ["https://prologis.gupy.io"],
    "ID Logistics": ["https://idlogistics.gupy.io"],
    "Penske Logistics": ["https://penske.gupy.io"],
    "Aliansce Sonae": ["https://alianscesonae.gupy.io"],
    "Allos": ["https://carreiras.gupy.io/allos"],
    "LOG Commercial Properties": ["https://logcp.gupy.io"],
    "BR Properties": ["https://brproperties.gupy.io"],
    "Auxiliadora Predial": ["https://auxiliadorapredial.gupy.io"],
    "Coelho da Fonseca": ["https://coelhodafonseca.gupy.io"],
    "RE/MAX": ["https://remax.gupy.io"],
    "Colliers": ["https://colliers.gupy.io"],
    "Newmark": ["https://newmark.gupy.io"],
    "Novonor": ["https://novonor.gupy.io"],
    "Odebrecht": ["https://novonor.gupy.io"],
    "Construcap": ["https://construcap.gupy.io"],
    "Mendes Júnior": ["https://mendesjunior.gupy.io"],
    "Galvão Engenharia": ["https://galvaoengenharia.gupy.io"],
    "Queiroz Galvão": ["https://queirozgalvao.gupy.io"],
    "PDG Realty": ["https://pdg.gupy.io"],
    "Rossi Residencial": ["https://rossi.gupy.io"],
    "Moura Dubeux": ["https://mouradubeux.gupy.io"],
    "RNI": ["https://rni.gupy.io"],
    "Cury": ["https://cury.gupy.io"],
    "Living": ["https://living.gupy.io"],
    "OAS": ["https://oas.gupy.io"],
    "Saint-Gobain": ["https://saintgobain.gupy.io"],
    "Holcim Brasil": ["https://holcim.gupy.io"],
    "Votorantim Cimentos": ["https://votorantimcimentos.gupy.io"],
    "Tigre": ["https://tigre.gupy.io"],
    "Amanco": ["https://amanco.gupy.io"],
    "Deca": ["https://deca.gupy.io"],
    "Roca Brasil": ["https://roca.gupy.io"],
    "Knauf": ["https://knauf.gupy.io"],
    "Eternit": ["https://eternit.gupy.io"],
    "Owens Corning": ["https://owenscorning.gupy.io"],
    "Whirlpool Brasil": ["https://whirlpool.gupy.io"],
    "Electrolux Brasil": ["https://electrolux.gupy.io"],
    "Mondial": ["https://mondial.gupy.io"],
    "Britânia": ["https://britania.gupy.io"],
    "Cadence": ["https://cadence.gupy.io"],
    "Arno": ["https://arno.gupy.io"],
    "Mueller Eletrodomésticos": ["https://mueller.gupy.io"],
    "Bosch Brasil": ["https://bosch.gupy.io"],
    "Siemens Brasil": ["https://siemens.gupy.io"],
    "ABB Brasil": ["https://abb.gupy.io"],
    "Schneider Electric Brasil": ["https://schneider.gupy.io"],
    "Romi": ["https://romi.gupy.io"],
    "AEL Sistemas": ["https://ael.gupy.io"],
    "Atech": ["https://atech.gupy.io"],
    "Avibras": ["https://avibras.gupy.io"],
    "Helibras": ["https://helicopteros.gupy.io"],
    "Eve Air Mobility": ["https://eveairmobility.gupy.io"],
    "Caoa Chery": ["https://caoa.gupy.io"],
    "BYD Brasil": ["https://byd.gupy.io"],
    "GWM Brasil": ["https://gwm.gupy.io"],
    "Flex Brasil": ["https://flex.gupy.io"],
    "Jabil Brasil": ["https://jabil.gupy.io"],
    "Continental Brasil": ["https://continental.gupy.io"],
    "ZF do Brasil": ["https://zf.gupy.io"],
    "Mahle": ["https://mahle.gupy.io"],
    "Eaton": ["https://eaton.gupy.io"],
    "Magneti Marelli": ["https://magneti.gupy.io"],
    "Eldorado Brasil": ["https://eldorado.gupy.io"],
    "Bracell": ["https://bracell.gupy.io"],
    "Irani": ["https://irani.gupy.io"],
    "International Paper Brasil": ["https://internationalpaper.gupy.io"],
    "Smurfit Kappa": ["https://smurfitkappa.gupy.io"],
    "Verallia": ["https://verallia.gupy.io"],
    "Cebrace": ["https://cebrace.gupy.io"],
    "AGC Brasil": ["https://agc.gupy.io"],
    "Unipar": ["https://unipar.gupy.io"],
    "Lanxess": ["https://lanxess.gupy.io"],
    "Clariant": ["https://clariant.gupy.io"],
    "Evonik": ["https://evonik.gupy.io"],
    "AkzoNobel": ["https://akzonobel.gupy.io"],
    "Sherwin-Williams": ["https://sherwinwilliams.gupy.io"],
    "PPG": ["https://ppg.gupy.io"],
    "Suvinil": ["https://suvinil.gupy.io"],
    "Tintas Coral": ["https://coral.gupy.io"],
    "Aperam": ["https://aperam.gupy.io"],
    "Ternium Brasil": ["https://ternium.gupy.io"],
    "Ferbasa": ["https://ferbasa.gupy.io"],
    "Paranapanema": ["https://paranapanema.gupy.io"],
    "Mangels": ["https://mangels.gupy.io"],
    "Caraíba Metais": ["https://caraiba.gupy.io"],
    "Votorantim": ["https://votorantim.gupy.io"],
    "InterCement": ["https://intercement.gupy.io"],
    "Cimento Tupi": ["https://cimentotupi.gupy.io"],
    "Cimento Itambé": ["https://cimentoitambe.gupy.io"],
    "LafargeHolcim": ["https://holcim.gupy.io"],
    "Brasilit": ["https://brasilit.gupy.io"],
    "Duratex": ["https://duratex.gupy.io"],
    "Sonae Sierra Brasil": ["https://sonaesierra.gupy.io"],
    "Mondi": ["https://mondi.gupy.io"],
    "Stora Enso": ["https://storaenso.gupy.io"],
    "Sylvamo": ["https://sylvamo.gupy.io"],
    "Owens Illinois": ["https://owensillinois.gupy.io"],
    "Wheaton Brasil": ["https://wheaton.gupy.io"],
    "Guardian Industries": ["https://guardian.gupy.io"],
    "Vivix Vidros": ["https://vivix.gupy.io"],
    "Petrocoque": ["https://petrocoque.gupy.io"],
    "Solvay": ["https://solvay.gupy.io"],
    "Arkema": ["https://arkema.gupy.io"],
    "DuPont Brasil": ["https://dupont.gupy.io"],
    "Adama Brasil": ["https://adama.gupy.io"],
    "FMC Brasil": ["https://fmc.gupy.io"],
    "UPL": ["https://upl.gupy.io"],
    "Nufarm": ["https://nufarm.gupy.io"],
    "Albaugh": ["https://albaugh.gupy.io"],
    "Biotrop": ["https://biotrop.gupy.io"],
    "ICL Brasil": ["https://icl.gupy.io"],
    "Galvani": ["https://galvani.gupy.io"],
    "OCP Brasil": ["https://ocp.gupy.io"],
    "Ferrero Brasil": ["https://ferrero.gupy.io"],
    "Mars Brasil": ["https://mars.gupy.io"],
    "Kraft Heinz": ["https://kraftheinz.gupy.io"],
    "Kellogg's": ["https://kelloggs.gupy.io"],
    "Mondelez": ["https://mondelez.gupy.io"],
    "Nestlé": ["https://nestle.gupy.io"],
    "Danone": ["https://danone.gupy.io"],
    "Lactalis": ["https://lactalis.gupy.io"],
    "Tnuva": ["https://tnuva.gupy.io"],
    "Pif Paf": ["https://pifpaf.gupy.io"],
    "Plena Alimentos": ["https://plena.gupy.io"],
    "Pamplona Alimentos": ["https://pamplona.gupy.io"],
    "Frigol": ["https://frigol.gupy.io"],
    "Tyson Foods Brasil": ["https://tyson.gupy.io"],
    "Coamo": ["https://coamo.gupy.io"],
    "Coopavel": ["https://coopavel.gupy.io"],
    "C.Vale": ["https://cvale.gupy.io"],
    "Coopercitrus": ["https://coopercitrus.gupy.io"],
    "Castrolanda": ["https://castrolanda.gupy.io"],
    "Cocamar": ["https://cocamar.gupy.io"],
    "Cotrijal": ["https://cotrijal.gupy.io"],
    "Lar Cooperativa Agroindustrial": ["https://lar.gupy.io"],
    "Adecoagro": ["https://adecoagro.gupy.io"],
    "Terra Santa": ["https://terrasanta.gupy.io"],
    "Tres Tentos": ["https://3tentos.gupy.io"],
    "Stara": ["https://stara.gupy.io"],
    "Valtra": ["https://valtra.gupy.io"],
    "Massey Ferguson": ["https://masseyferguson.gupy.io"],
    "AGCO": ["https://agco.gupy.io"],
    "Louis Dreyfus Company": ["https://ldc.gupy.io"],
    "COFCO International Brasil": ["https://cofco.gupy.io"],
    "Biosev": ["https://biosev.gupy.io"],
    "Cocal Energia": ["https://cocal.gupy.io"],
    "Coruripe": ["https://coruripe.gupy.io"],
    "Usina Santa Terezinha": ["https://santaterezinha.gupy.io"],
    "Cristal Pigmentos": ["https://cristal.gupy.io"],
    "Sealed Air": ["https://sealedair.gupy.io"],
    "Tetra Pak": ["https://tetrapak.gupy.io"],
    "Catalent": ["https://catalent.gupy.io"],
    "Bacardi Brasil": ["https://bacardi.gupy.io"],
    "Beam Suntory": ["https://beamsuntory.gupy.io"],
    "Edrington": ["https://edrington.gupy.io"],
    "Zamp": ["https://zamp.gupy.io"],
    "Bob's": ["https://bobs.gupy.io"],
    "Habib's": ["https://habibs.gupy.io"],
    "Giraffas": ["https://giraffas.gupy.io"],
    "Subway": ["https://subway.gupy.io"],
    "Domino's Pizza": ["https://dominos.gupy.io"],
    "Pizza Hut": ["https://pizzahut.gupy.io"],
    "KFC": ["https://kfc.gupy.io"],
    "Outback Steakhouse": ["https://outback.gupy.io"],
    "Madero": ["https://madero.gupy.io"],
    "Spoleto": ["https://spoleto.gupy.io"],
    "Vivenda do Camarão": ["https://vivenda.gupy.io"],
    "China in Box": ["https://chinainbox.gupy.io"],
    "Kopenhagen": ["https://kopenhagen.gupy.io"],
    "Chocolates Garoto": ["https://garoto.gupy.io"],
    "The Coffee": ["https://thecoffee.gupy.io"],
    "Casa do Pão de Queijo": ["https://casadopaodequeijo.gupy.io"],
    "Dunkin Donuts": ["https://dunkin.gupy.io"],
    "TotalPass": ["https://totalpass.gupy.io"],
    "Concentrix": ["https://concentrix.gupy.io"],
    "Webhelp": ["https://webhelp.gupy.io"],
    "Foundever": ["https://foundever.gupy.io"],
    "Sitel": ["https://sitel.gupy.io"],
    "AeC": ["https://aec.gupy.io"],
    "CSU Cardsystem": ["https://csu.gupy.io"],
    "Almaviva do Brasil": ["https://almaviva.gupy.io"],
    "GR Serviços": ["https://grservicos.gupy.io"],
    "Protiviti": ["https://protiviti.gupy.io"],
    "Falconi": ["https://falconi.gupy.io"],
    "Integration Consulting": ["https://integration.gupy.io"],
    "RSM Brasil": ["https://rsm.gupy.io"],
    "BDO": ["https://bdo.gupy.io"],
    "Grant Thornton": ["https://grantthornton.gupy.io"],
    "Mazars": ["https://mazars.gupy.io"],
    "Crowe": ["https://crowe.gupy.io"],
    "Hays Brasil": ["https://hays.gupy.io"],
    "Michael Page": ["https://michaelpage.gupy.io"],
    "PageGroup": ["https://pagegroup.gupy.io"],
    "Korn Ferry": ["https://kornferry.gupy.io"],
    "Spencer Stuart": ["https://spencerstuart.gupy.io"],
    "Heidrick & Struggles": ["https://heidrick.gupy.io"],
    "Egon Zehnder": ["https://egonzehnder.gupy.io"],
    "Russell Reynolds": ["https://russellreynolds.gupy.io"],
    "Roland Berger": ["https://rolandberger.gupy.io"],
    "Oliver Wyman": ["https://oliverwyman.gupy.io"],
    "Kearney": ["https://kearney.gupy.io"],
    "AT Kearney": ["https://kearney.gupy.io"],
    "Booz Allen": ["https://boozallen.gupy.io"],
    "Solvi": ["https://solvi.gupy.io"],
    "Estre Ambiental": ["https://estreambiental.gupy.io"],
    "Orizon": ["https://orizon.gupy.io"],
    "Foxx": ["https://foxx.gupy.io"],
    "GS Inima": ["https://gsinima.gupy.io"],
    "Águas do Brasil": ["https://aguasdobrasil.gupy.io"],
    "Iguá Saneamento": ["https://igua.gupy.io"],
    "Cedae": ["https://cedae.gupy.io"],
    "Caesb": ["https://caesb.gupy.io"],
    "Compesa": ["https://compesa.gupy.io"],
    "Embasa": ["https://embasa.gupy.io"],
    "Casan": ["https://casan.gupy.io"],
    "Cagece": ["https://cagece.gupy.io"],
    "Naturgy": ["https://naturgy.gupy.io"],
    "Galp Brasil": ["https://galp.gupy.io"],
    "Shell Brasil": ["https://shell.gupy.io"],
    "Total Energies Brasil": ["https://totalenergies.gupy.io"],
    "Equinor": ["https://equinor.gupy.io"],
    "BP Brasil": ["https://bp.gupy.io"],
    "Chevron Brasil": ["https://chevron.gupy.io"],
    "ExxonMobil Brasil": ["https://exxonmobil.gupy.io"],
    "Karoon Energy": ["https://karoon.gupy.io"],
    "Statkraft Brasil": ["https://statkraft.gupy.io"],
    "Voltalia": ["https://voltalia.gupy.io"],
    "Acciona": ["https://acciona.gupy.io"],
    "EDF Norte Fluminense": ["https://edf.gupy.io"],
    "ERG Brasil": ["https://erg.gupy.io"],
    "AES Tietê": ["https://aestiete.gupy.io"],
    "Omega Energia": ["https://omegaenergia.gupy.io"],
    "Casa dos Ventos": ["https://casadosventos.gupy.io"],
    "Renova Energia": ["https://renovaenergia.gupy.io"],
    "Iberdrola": ["https://iberdrola.gupy.io"],
    "Brisanet": ["https://brisanet.gupy.io"],
    "Desktop": ["https://desktop.gupy.io"],
    "Unifique": ["https://unifique.gupy.io"],
    "Vero Internet": ["https://vero.gupy.io"],
    "Sercomtel": ["https://sercomtel.gupy.io"],
    "Copel Telecom": ["https://copeltelecom.gupy.io"],
    "Embratel": ["https://embratel.gupy.io"],
    "Alloha Fibra": ["https://allohafibra.gupy.io"],
    "Grupo Bandeirantes": ["https://band.gupy.io"],
    "RedeTV": ["https://redetv.gupy.io"],
    "BandNews": ["https://bandnews.gupy.io"],
    "Rádio Globo": ["https://radioglobo.gupy.io"],
    "Grupo Abril": ["https://abril.gupy.io"],
    "Grupo Estado": ["https://estadao.gupy.io"],
    "O Estado de S. Paulo": ["https://estadao.gupy.io"],
    "Grupo Folha": ["https://folha.gupy.io"],
    "Folha de S.Paulo": ["https://folha.gupy.io"],
    "Valor Econômico": ["https://valor.gupy.io"],
    "InfoMoney": ["https://infomoney.gupy.io"],
    "Exame": ["https://exame.gupy.io"],
    "Veja": ["https://veja.gupy.io"],
    "Editora Globo": ["https://editoraglobo.gupy.io"],
    "Editora Record": ["https://editorarecord.gupy.io"],
    "Editora Saraiva": ["https://saraiva.gupy.io"],
    "FTD Educação": ["https://ftd.gupy.io"],
    "Moderna": ["https://moderna.gupy.io"],
    "Ática": ["https://atica.gupy.io"],
    "Scipione": ["https://scipione.gupy.io"],
    "McGraw Hill Brasil": ["https://mcgrawhill.gupy.io"],
    "Cengage Brasil": ["https://cengage.gupy.io"],
    "Wiley Brasil": ["https://wiley.gupy.io"],
    "Springer Nature": ["https://springernature.gupy.io"],
    "Coursera": ["https://careers.coursera.com"],
    "Udemy": ["https://about.udemy.com/careers"],
    "Duolingo": ["https://careers.duolingo.com"],
    "Open English": ["https://openenglish.gupy.io"],
    "EF Education First": ["https://careers.ef.com"],
    "Cultura Inglesa": ["https://culturainglesa.gupy.io"],
    "Yázigi": ["https://yazigi.gupy.io"],
    "Anglo": ["https://anglo.gupy.io"],
    "Etapa": ["https://etapa.gupy.io"],
    "Objetivo": ["https://objetivo.gupy.io"],
    "Poliedro": ["https://poliedro.gupy.io"],
    "Sistema COC": ["https://coc.gupy.io"],
    "Conquer": ["https://conquer.gupy.io"],
    "Geekie": ["https://geekie.gupy.io"],
    "Stoodi": ["https://stoodi.gupy.io"],
    "DIO": ["https://dio.gupy.io"],
    "Cubos Academy": ["https://cubos.gupy.io"],
    "PM3": ["https://pm3.gupy.io"],
    "Mentorama": ["https://mentorama.gupy.io"],
    "Tera": ["https://tera.gupy.io"],
    "Reprograma": ["https://reprograma.gupy.io"],
    "PrograMaria": ["https://programaria.gupy.io"],
    "Kenzie Academy": ["https://kenzie.gupy.io"],
    "Digital Innovation One": ["https://dio.gupy.io"],
    "Savegnago": ["https://savegnago.gupy.io"],
    "Comper": ["https://comper.gupy.io"],
    "Bistek": ["https://bistek.gupy.io"],
    "Zaffari": ["https://zaffari.gupy.io"],
    "Muffato": ["https://muffato.gupy.io"],
    "Cooperativa Santa Clara": ["https://santaclara.gupy.io"],
    "Cooperativa Três Tentos": ["https://3tentos.gupy.io"],
    "Cutrale": ["https://cutrale.gupy.io"],
    "Friboi": ["https://friboi.gupy.io"],
    "São Paulo Turismo": ["https://saopauloturismo.gupy.io"],
    "Metrô São Paulo": ["https://metrosp.gupy.io"],
    "Ailos Sistema": ["https://ailos.gupy.io"],
    "Sicredi": ["https://sicredi.gupy.io"],
    "Unicred": ["https://unicred.gupy.io"],
    "BB Seguridade": ["https://bbseguridade.gupy.io"],
    "Caixa Seguridade": ["https://caixaseguridade.gupy.io"],
    "Brasilprev": ["https://brasilprev.gupy.io"],
    "Brasilcap": ["https://brasilcap.gupy.io"],
    "Capemisa": ["https://capemisa.gupy.io"],
    "Chubb": ["https://chubb.gupy.io"],
    "AIG": ["https://aig.gupy.io"],
    "Willis Towers Watson": ["https://wtw.gupy.io"],
    "Liberty Seguros": ["https://liberty.gupy.io"],
    "Cetelem": ["https://cetelem.gupy.io"],
    "Santander Consumer": ["https://santanderconsumer.gupy.io"],
    "Renner Card": ["https://rennercard.gupy.io"],
    "Cred-System": ["https://credsystem.gupy.io"],
    "Banco Olé": ["https://ole.gupy.io"],
    "Banco Cetelem": ["https://cetelem.gupy.io"],
    "Banco da China Brasil": ["https://bankofchina.gupy.io"],
    "Banco Rabobank International Brasil": ["https://rabobank.gupy.io"],
    "Sumitomo Mitsui": ["https://sumitomo.gupy.io"],
    "MUFG Brasil": ["https://mufg.gupy.io"],
    "Mizuho": ["https://mizuho.gupy.io"],
    "Scotiabank": ["https://scotiabank.gupy.io"],
    "Deutsche Bank": ["https://careers.db.com"],
    "Deutsche Bank Brasil": ["https://careers.db.com"],
    "Citibank Brasil": ["https://citibank.gupy.io"],
    "Morgan Stanley": ["https://morganstanley.gupy.io"],
    "Goldman Sachs": ["https://goldmansachs.gupy.io"],
    "JP Morgan": ["https://jpmorgan.gupy.io"],
    "Credit Suisse": ["https://creditsuisse.gupy.io"],
    "UBS BB": ["https://ubs.gupy.io"],
    "HSBC Brasil": ["https://hsbc.gupy.io"],
    "Banco Bocom BBM": ["https://bocom.gupy.io"],
    "Banco Cifra": ["https://cifra.gupy.io"],
    "Banco Paulista": ["https://paulista.gupy.io"],
    "Banco Guanabara": ["https://guanabara.gupy.io"],
    "ABC Brasil": ["https://abcbrasil.gupy.io"],
    "Banestes": ["https://banestes.gupy.io"],
    "Banrisul": ["https://banrisul.gupy.io"],
    "BRB": ["https://brb.gupy.io"],
    "Paraná Banco": ["https://paranabanco.gupy.io"],
    "Banco Pine": ["https://bancopine.gupy.io"],
    "Banco Sofisa": ["https://sofisa.gupy.io"],
    "Banco Daycoval": ["https://daycoval.gupy.io"],
    "Banco BV": ["https://bancobv.gupy.io"],
    "Banco BMG": ["https://bancobmg.gupy.io"],
    "Banco Pan": ["https://bancopan.gupy.io"],
    "Banco Modal": ["https://modal.gupy.io"],
    "Banco BS2": ["https://bs2.gupy.io"],
    "Banco Topázio": ["https://topazio.gupy.io"],
    "Banco Master": ["https://master.gupy.io"],
    "Banco Semear": ["https://semear.gupy.io"],
    "Banco Rendimento": ["https://rendimento.gupy.io"],
    "Banco Rodobens": ["https://rodobens.gupy.io"],
    "Banco Industrial": ["https://bancoindustrial.gupy.io"],
    "Banco Fibra": ["https://fibra.gupy.io"],
    "Banco Bari": ["https://bari.gupy.io"],
    "Banco BMP": ["https://bmp.gupy.io"],
    "Banco Digimais": ["https://digimais.gupy.io"],
    "Banco do Nordeste": ["https://bndes.gupy.io"],
    "Banco da Amazônia": ["https://basa.gupy.io"],
    "Banese": ["https://banese.gupy.io"],
    "Banpará": ["https://banpara.gupy.io"],
    "BNDES": ["https://bndes.gupy.io"],
    "Caixa Econômica Federal": ["https://caixa.gupy.io"],
    "Banco do Brasil": ["https://bb.gupy.io"],
    "Bradesco": ["https://bradesco.gupy.io"],
    "Itaú": ["https://vemproitau.gupy.io"],
    "Santander": ["https://santander.gupy.io"],
    "Safra": ["https://venhasersafra.gupy.io"],
    "Inter": ["https://boards.greenhouse.io/inter"],
    "Nubank": ["https://boards.greenhouse.io/nubank"],
    "C6 Bank": ["https://boards.greenhouse.io/c6bank"],
    "BTG Pactual": ["https://boards.greenhouse.io/btgpactual"],
    "XP Inc": ["https://boards.greenhouse.io/xpinc"],
    "Stone": ["https://stone.gupy.io"],
    "PagSeguro": ["https://pagseguro.gupy.io"],
    "PicPay": ["https://carreiras.gupy.io/picpay"],
    "Mercado Pago": ["https://mercadopago.gupy.io"],
    "PagBank": ["https://carreiras.gupy.io/pagbank"],
    "Cielo": ["https://cielo.gupy.io"],
    "Rede": ["https://rede.gupy.io"],
    "Getnet": ["https://carreiras.gupy.io/getnet"],
    "SumUp Brasil": ["https://sumup.gupy.io"],
    "American Express": ["https://aexp.eightfold.ai/careers"],
    "Visa": ["https://careers.smartrecruiters.com/Visa"],
    "Mastercard": ["https://careers.mastercard.com"],
    "Western Union": ["https://careers.westernunion.com"],
    "Wise": ["https://wise.jobs"],
    "Avenue": ["https://avenue.gupy.io"],
    "Empiricus": ["https://empiricus.gupy.io"],
    "Suno Research": ["https://suno.gupy.io"],
    "StatusInvest": ["https://statusinvest.gupy.io"],
    "Kapitalo": ["https://kapitalo.gupy.io"],
    "Garde": ["https://garde.gupy.io"],
    "Ibiuna": ["https://ibiuna.gupy.io"],
    "Legacy Capital": ["https://legacy.gupy.io"],
    "Dynamo": ["https://dynamo.gupy.io"],
    "Atmos Capital": ["https://atmos.gupy.io"],
    "Opportunity": ["https://opportunity.gupy.io"],
    "BR Partners": ["https://brpartners.gupy.io"],
    "Adam Capital": ["https://adam.gupy.io"],
    "Verde Asset": ["https://verde.gupy.io"],
    "SPX Capital": ["https://spx.gupy.io"],
    "ARX": ["https://arx.gupy.io"],
    "Bozano Investimentos": ["https://bozano.gupy.io"],
    "Wright Capital": ["https://wright.gupy.io"],
    "Constellation": ["https://constellation.gupy.io"],
    "Truxt": ["https://truxt.gupy.io"],
    "Mosaico": ["https://mosaico.gupy.io"],
    "Konkero": ["https://konkero.gupy.io"],
    "Acordo Certo": ["https://acordocerto.gupy.io"],
    "Quero Quitar": ["https://queroquitar.gupy.io"],
    "FinanZero": ["https://finanzero.gupy.io"],
    "Geru": ["https://geru.gupy.io"],
    "Rebel": ["https://rebel.gupy.io"],
    "Just": ["https://just.gupy.io"],
    "Biva": ["https://biva.gupy.io"],
    "Bcredi": ["https://bcredi.gupy.io"],
    "Provu": ["https://provu.gupy.io"],
    "Trigg": ["https://trigg.gupy.io"],
    "Kavod Lending": ["https://kavod.gupy.io"],
    "Nibo": ["https://nibo.gupy.io"],
    "Conta Azul": ["https://contaazul.gupy.io"],
    "Bling": ["https://bling.gupy.io"],
    "Omie": ["https://omie.gupy.io"],
    "Contabilizei": ["https://contabilizei.gupy.io"],
    "BHub": ["https://bhub.gupy.io"],
    "Open Co": ["https://openc.gupy.io"],
    "Méliuz": ["https://meliuz.gupy.io"],
    "Remessa Online": ["https://remessaonline.gupy.io"],
    "MoneyGram": ["https://moneygram.gupy.io"],
    "Elo": ["https://elo.gupy.io"],
    "Hipercard": ["https://hipercard.gupy.io"],
    "Easynvest": ["https://easynvest.gupy.io"],
    "Modal": ["https://modalmais.gupy.io"],
    "Spiti": ["https://spiti.gupy.io"],
    "Levante Ideias": ["https://levante.gupy.io"],
    "Capital Aberto": ["https://capitalaberto.gupy.io"],
    "Brasil Plural": ["https://brasilplural.gupy.io"],
    "Banco Plural": ["https://brasilplural.gupy.io"],
    "Itaú Asset": ["https://itaúasset.gupy.io"],
    "Bradesco Asset": ["https://bradescoasset.gupy.io"],
    "BB Asset": ["https://bbasset.gupy.io"],
    "Santander Asset": ["https://santanderasset.gupy.io"],
    "Caixa Asset": ["https://caixaasset.gupy.io"],
    "Bradesco Vida e Previdência": ["https://bradescovida.gupy.io"],
    "Bradesco Seguros": ["https://bradescoseguros.gupy.io"],
    "Bradesco Saúde": ["https://bradescosaude.gupy.io"],
    "Itaú BBA": ["https://itau-bba.gupy.io"],
    "Banco Santander Brasil": ["https://santander.gupy.io"],
    "Banco Inter": ["https://boards.greenhouse.io/inter"],
    "Banco C6": ["https://boards.greenhouse.io/c6bank"],
    "Banco Guanabara": ["https://guanabara.gupy.io"],
    "Banco Mercantil": ["https://mercantil.gupy.io"],
    "Banco ABC": ["https://abcbrasil.gupy.io"],
    "Alfa Financeira": ["https://alfa.gupy.io"],
    "Asa": ["https://asa.gupy.io"],
    "Banco Digimais": ["https://digimais.gupy.io"],
    "Banco da China Brasil": ["https://bankofchina.gupy.io"],
    "Banco Rabobank International Brasil": ["https://rabobank.gupy.io"],
    "Banco Rendimento": ["https://rendimento.gupy.io"],
    "Banco Rodobens": ["https://rodobens.gupy.io"],
    "Banco Paulista": ["https://paulista.gupy.io"],
    "Banco Semear": ["https://semear.gupy.io"],
    "Banco Topázio": ["https://topazio.gupy.io"],
    "Banco Master": ["https://master.gupy.io"],
    "Banco Pine": ["https://bancopine.gupy.io"],
    "Banco Fibra": ["https://fibra.gupy.io"],
    "Banco Bari": ["https://bari.gupy.io"],
    "Banco BMP": ["https://bmp.gupy.io"],
    "Banco Industrial": ["https://bancoindustrial.gupy.io"],
    "Banco do Nordeste": ["https://bndes.gupy.io"],
    "Banco da Amazônia": ["https://basa.gupy.io"],
    "Banese": ["https://banese.gupy.io"],
    "Banpará": ["https://banpara.gupy.io"],
    "BNDES": ["https://bndes.gupy.io"],
    "Caixa Econômica Federal": ["https://caixa.gupy.io"],
    "Banco do Brasil": ["https://bb.gupy.io"],
    "Bradesco": ["https://bradesco.gupy.io"],
    "Itaú Unibanco": ["https://vemproitau.gupy.io"],
    "Santander Brasil": ["https://santander.gupy.io"],
    "Safra": ["https://venhasersafra.gupy.io"],
    "Inter": ["https://boards.greenhouse.io/inter"],
    "Nubank": ["https://boards.greenhouse.io/nubank"],
    "C6 Bank": ["https://boards.greenhouse.io/c6bank"],
    "BTG Pactual": ["https://boards.greenhouse.io/btgpactual"],
    "XP Inc": ["https://boards.greenhouse.io/xpinc"],
    "Stone": ["https://stone.gupy.io"],
    "PagSeguro": ["https://pagseguro.gupy.io"],
    "PicPay": ["https://carreiras.gupy.io/picpay"],
    "Mercado Pago": ["https://mercadopago.gupy.io"],
    "PagBank": ["https://carreiras.gupy.io/pagbank"],
    "Cielo": ["https://cielo.gupy.io"],
    "Rede": ["https://rede.gupy.io"],
    "Getnet": ["https://carreiras.gupy.io/getnet"],
    "SumUp Brasil": ["https://sumup.gupy.io"],
}


def load_existing_names() -> set[str]:
    names = set()
    with open(YAML_PATH, encoding="utf-8") as f:
        for c in yaml.safe_load(f).get("companies", []):
            names.add(normalize_name(c["name"]))
    with open(LIST_PATH, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            names.add(normalize_name(row["Nome da Empresa"]))
    return names


def load_candidates(existing: set[str]) -> list[tuple[str, str]]:
    seen = set()
    out: list[tuple[str, str]] = []

    def add(name: str, macro: str):
        key = normalize_name(name)
        if not key or key in seen or key in existing:
            return
        seen.add(key)
        out.append((name.strip(), macro))

    for name, macro, _ in COMPANY_SEEDS:
        add(name, macro)

    with open(ROOT / "data/seeds/associations_extra.yaml", encoding="utf-8") as f:
        for c in yaml.safe_load(f).get("companies", []):
            add(c["name"], c["macro"])

    for name, macro in EXPAND_COMPANIES:
        add(name, macro)

    try:
        resp = requests.get("https://brapi.dev/api/quote/list", timeout=30)
        resp.raise_for_status()
        sector_map = {
            "Finance": "Financeiro",
            "Energy Minerals": "Energia e Utilities",
            "Utilities": "Energia e Utilities",
            "Technology Services": "Tecnologia",
            "Retail Trade": "Varejo e Consumo",
            "Health Technology": "Saúde",
            "Producer Manufacturing": "Indústria",
            "Transportation": "Logística e Mobilidade",
            "Consumer Non-Durables": "Varejo e Consumo",
            "Commercial Services": "Serviços e Outros",
            "Non-Energy Minerals": "Indústria",
            "Process Industries": "Indústria",
            "Consumer Durables": "Varejo e Consumo",
            "Distribution Services": "Varejo e Consumo",
            "Communications": "Energia e Utilities",
            "Industrial Services": "Indústria",
            "Health Services": "Saúde",
            "Electronic Technology": "Tecnologia",
            "Consumer Services": "Varejo e Consumo",
        }
        for s in resp.json().get("stocks", []):
            if s.get("type") != "stock":
                continue
            raw = (s.get("name") or "").strip()
            raw = re.sub(r"\s*-\s*BRASIL.*$", "", raw, flags=re.I)
            raw = re.sub(r"\s*S\.?A\.?\s*$", "", raw, flags=re.I)
            raw = re.sub(r"\s*BOLSA.*$", "", raw, flags=re.I)
            raw = re.sub(r"\s*BCO\s+", "Banco ", raw, flags=re.I)
            raw = re.sub(r"\s*CIA\s+", "Companhia ", raw, flags=re.I)
            name = raw.title() if raw.isupper() else raw
            macro = sector_map.get(s.get("sector", ""), "Serviços e Outros")
            add(name, macro)
    except requests.RequestException as exc:
        print(f"brapi skip: {exc}")

    return out


_guesser_path = ROOT / "scripts/fix_vagas_urls_guesser.py"
_spec = importlib.util.spec_from_file_location("fix_vagas_urls_guesser", _guesser_path)
_guesser = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_guesser)

from src.py.functions.portal_verification import verify_portal_has_jobs


def curated_candidates(name: str) -> list[str]:
    urls = []
    for key, vals in CURATED_URLS.items():
        if normalize_name(key) == normalize_name(name):
            urls.extend(vals)
    return [clean_url(u) for u in urls]


def discover_with_curated(name: str, macro: str, session, cache: dict) -> dict | None:
    from scripts.discover_career_urls import discover_one as base_discover

    extra = curated_candidates(name)
    if extra:
        for url in extra:
            if verify_website_status(session, url)["status"] != "1":
                continue
            if not verify_portal_has_jobs(url, session):
                continue
            if ".gupy.io" in url.lower() and not _slug_matches_url(name, url):
                # slugs criativos: aceita se portal tem jobs e não é genérico
                final = url.lower()
                if final.rstrip("/") in ("https://carreiras.gupy.io", "https://portal.gupy.io"):
                    continue
            return {
                "name": name,
                "macro": macro,
                "urls": _collect_urls(name, url, extra),
            }

    res = base_discover(name, macro, session, cache)
    if res.get("URL"):
        return {
            "name": name,
            "macro": macro,
            "urls": _collect_urls(name, res["URL"], curated_candidates(name)),
        }
    return None


def _collect_urls(name: str, primary: str, fallbacks: list[str]) -> list[str]:
    primary = clean_url(primary)
    urls = [primary]
    for u in fallbacks:
        u = clean_url(u)
        if u != primary and u not in urls:
            urls.append(u)
        if len(urls) >= 3:
            break
    return urls[:3]


def render_yaml(entries: list[dict]) -> str:
    by_macro: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_macro[e["macro"]].append(e)

    order = [
        "Financeiro",
        "Tecnologia",
        "Varejo e Consumo",
        "Saúde",
        "Indústria",
        "Energia e Utilities",
        "Logística e Mobilidade",
        "Construção e Imóveis",
        "Educação",
        "Agro e Alimentos",
        "Mídia e Entretenimento",
        "Serviços e Outros",
    ]

    lines = [
        "# === Lote curado: B3 + Valor 1000 + Multinacionais BR ===",
        "# Fonte: B3 (jun/2026), Valor 1000 (ed. 2025), Fortune Global 500",
        "",
    ]
    for macro in order:
        items = by_macro.get(macro, [])
        if not items:
            continue
        lines.append(f"# --- {macro} ---")
        for item in sorted(items, key=lambda x: x["name"].lower()):
            lines.append(f"- name: {item['name']}")
            lines.append(f"  macro: {macro}")
            lines.append("  urls:")
            for url in item["urls"]:
                lines.append(f"  - {url}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main():
    existing = load_existing_names()
    candidates = load_candidates(existing)
    print(f"Candidatos únicos (fora YAML+CSV): {len(candidates)}")

    cache = load_cache()
    session = create_shared_session()
    verified: list[dict] = []
    done = 0

    def work(item):
        name, macro = item
        return discover_with_curated(name, macro, session, cache)

    with ThreadPoolExecutor(max_workers=16) as pool:
        futures = {pool.submit(work, c): c for c in candidates}
        for fut in as_completed(futures):
            done += 1
            res = fut.result()
            if res:
                verified.append(res)
                print(f"+ [{len(verified)}] {res['name']} -> {res['urls'][0]}")
            if done % 100 == 0:
                print(f"  progresso {done}/{len(candidates)} verificados={len(verified)}")
                save_cache(cache)

    save_cache(cache)

    if len(verified) > TARGET_MAX:
        verified = verified[:TARGET_MAX]

    print(f"\nVerificadas: {len(verified)} (alvo {TARGET_MIN}-{TARGET_MAX})")
    yaml_text = render_yaml(verified)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(yaml_text, encoding="utf-8")
    print(f"Batch YAML -> {OUT_PATH}")

    if len(verified) < TARGET_MIN:
        print(f"AVISO: abaixo do mínimo ({TARGET_MIN})")


if __name__ == "__main__":
    main()
