#!/usr/bin/env python3
"""Expande list.csv com empresas grandes (B3, Valor 1000, multinacionais BR).

Estratégia:
- Lista curada de ~1500 empresas grandes brasileiras / multinacionais com operação BR
- Para cada empresa não-presente, tenta múltiplos padrões ATS em paralelo
- Adiciona somente URLs verificadas (HTTP 2xx/3xx + heurística anti-portal-genérico)
"""

import concurrent.futures
import csv
import os
import sys
import unicodedata
from datetime import date

import requests
import urllib3

urllib3.disable_warnings()

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from scripts.segment_macro_map import to_macro
from src.py.functions.df_operations import clean_url

LIST_PATH = os.path.join(ROOT, "src/data/input/list.csv")
FIELDNAMES = [
    "Status da URL",
    "Data de Entrada",
    "Nome da Empresa",
    "Segmento da Empresa",
    "Plataforma",
    "URL",
]

HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}


def slugify(name: str) -> str:
    n = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode().lower()
    n = "".join(c if c.isalnum() or c == " " else " " for c in n)
    return " ".join(n.split())


def slug_variants(name: str) -> list[str]:
    """Variantes de alta confiança apenas (evita colisões com palavras genéricas)."""
    s = slugify(name)
    if not s:
        return []
    words = s.split()
    no_space = "".join(words)
    dashed = "-".join(words)
    grupo = [w for w in words if w not in {"grupo", "group", "do", "da", "de"}]
    grupo_ns = "".join(grupo)
    grupo_ds = "-".join(grupo)
    variants = {no_space, dashed, grupo_ns, grupo_ds}
    variants.discard("")
    # Slugs muito curtos (<5 chars) só passam se o próprio nome inteiro for curto
    full_short = len(no_space) < 5
    return [v for v in variants if (4 <= len(v) <= 50) or (full_short and v == no_space)]


def candidate_urls(name: str) -> list[str]:
    urls = []
    for s in slug_variants(name):
        urls.extend(
            [
                f"https://{s}.gupy.io",
                f"https://jobs.kenoby.com/{s}",
                f"https://jobs.lever.co/{s}",
                f"https://{s}.teamtailor.com",
            ]
        )
    # dedup keep order
    seen = set()
    out = []
    for u in urls:
        if u not in seen:
            seen.add(u)
            out.append(u)
    return out


def detect_platform(url: str) -> str:
    u = url.lower()
    if ".gupy.io" in u or "gupy.io/" in u:
        return "Gupy"
    if "greenhouse.io" in u:
        return "Greenhouse"
    if "lever.co" in u:
        return "Lever"
    if "inhire" in u:
        return "InHire"
    if "solides.jobs" in u:
        return "SOLIDES"
    if "kenoby" in u:
        return "Kenoby"
    if "recruitee" in u:
        return "Recruitee"
    if "workable" in u:
        return "Workable"
    if "bamboohr" in u:
        return "BambooHR"
    if "teamtailor" in u:
        return "TeamTailor"
    if "pandape" in u or "infojobs" in u:
        return "InfoJobs"
    return "Site da Empresa"


GENERIC_BLOCK = (
    "carreiras.gupy.io",
    "portal.gupy.io",
    "boards.greenhouse.io/embed",
)


def try_url(session, url: str) -> str | None:
    try:
        r = session.get(url, timeout=6, allow_redirects=True, verify=False)
    except Exception:
        return None
    if not (200 <= r.status_code < 400):
        return None
    final = r.url.lower().rstrip("/")
    if final in ("https://carreiras.gupy.io", "https://portal.gupy.io"):
        return None
    if "solides.jobs" in final and "notfound" in final:
        return None
    if "greenhouse.io" in final and final.endswith("greenhouse.io"):
        return None
    if "kenoby.com" in final and "jobs.kenoby.com" not in final:
        return None
    # Rejeita quando o pattern redireciona para fora do ATS original (ex.: teamtailor → karriar.audi.se).
    src = url.lower()
    if ".teamtailor.com" in src and ".teamtailor.com" not in final:
        return None
    if "lever.co" in src and "lever.co" not in final:
        return None
    if ".gupy.io" in src and ".gupy.io" not in final:
        return None
    return clean_url(r.url)


def find_url_for(name: str, session) -> str | None:
    for url in candidate_urls(name):
        found = try_url(session, url)
        if found:
            return found
    return None


# ---------------------------------------------------------------------------
# Lista curada de grandes empresas brasileiras + multinacionais com operação BR.
# Cada item: (Nome, Segmento Macro)
# ---------------------------------------------------------------------------

COMPANIES: list[tuple[str, str]] = [
    # --- Financeiro: bancos, fintechs, seguradoras, corretoras, pagamentos ---
    ("Banco BV", "Financeiro"),
    ("Banco Votorantim", "Financeiro"),
    ("BTG Pactual", "Financeiro"),
    ("Banco Original", "Financeiro"),
    ("Banco Pan", "Financeiro"),
    ("Banco BMG", "Financeiro"),
    ("Banco Daycoval", "Financeiro"),
    ("Banco Sofisa", "Financeiro"),
    ("Banco Modal", "Financeiro"),
    ("Banco Pine", "Financeiro"),
    ("Banco Fibra", "Financeiro"),
    ("Banco Mercantil do Brasil", "Financeiro"),
    ("Banco ABC Brasil", "Financeiro"),
    ("Banco Industrial", "Financeiro"),
    ("Banco Bari", "Financeiro"),
    ("Banco BS2", "Financeiro"),
    ("Banco Topázio", "Financeiro"),
    ("Banco Master", "Financeiro"),
    ("Banco Semear", "Financeiro"),
    ("Banco do Nordeste", "Financeiro"),
    ("Banco da Amazônia", "Financeiro"),
    ("Banese", "Financeiro"),
    ("BRDE", "Financeiro"),
    ("Banpará", "Financeiro"),
    ("BNDES", "Financeiro"),
    ("BB DTVM", "Financeiro"),
    ("Bradesco", "Financeiro"),
    ("Bradesco Saúde", "Financeiro"),
    ("Bradesco Seguros", "Financeiro"),
    ("Itaú", "Financeiro"),
    ("Itaú BBA", "Financeiro"),
    ("Itaú Unibanco", "Financeiro"),
    ("Santander Brasil", "Financeiro"),
    ("Banco do Brasil", "Financeiro"),
    ("Caixa Econômica Federal", "Financeiro"),
    ("Safra", "Financeiro"),
    ("HSBC Brasil", "Financeiro"),
    ("Citibank Brasil", "Financeiro"),
    ("Deutsche Bank", "Financeiro"),
    ("Morgan Stanley", "Financeiro"),
    ("Goldman Sachs", "Financeiro"),
    ("JP Morgan", "Financeiro"),
    ("Credit Suisse", "Financeiro"),
    ("UBS BB", "Financeiro"),
    ("Banco Bocom BBM", "Financeiro"),
    ("Banco Cifra", "Financeiro"),
    ("Sumitomo Mitsui", "Financeiro"),
    ("MUFG Brasil", "Financeiro"),
    ("Mizuho", "Financeiro"),
    ("Scotiabank", "Financeiro"),
    ("Rabobank Brasil", "Financeiro"),
    ("Inter", "Financeiro"),
    ("Banco Inter", "Financeiro"),
    ("Nubank", "Financeiro"),
    ("C6 Bank", "Financeiro"),
    ("Neon", "Financeiro"),
    ("Original", "Financeiro"),
    ("Next", "Financeiro"),
    ("Will Bank", "Financeiro"),
    ("PicPay", "Financeiro"),
    ("Mercado Pago", "Financeiro"),
    ("PagSeguro", "Financeiro"),
    ("PagBank", "Financeiro"),
    ("Stone", "Financeiro"),
    ("Stone Co", "Financeiro"),
    ("Cielo", "Financeiro"),
    ("Rede", "Financeiro"),
    ("Getnet", "Financeiro"),
    ("Sumup", "Financeiro"),
    ("SumUp Brasil", "Financeiro"),
    ("Vindi", "Financeiro"),
    ("Iugu", "Financeiro"),
    ("Pagar.me", "Financeiro"),
    ("Pagarme", "Financeiro"),
    ("Asaas", "Financeiro"),
    ("Cora", "Financeiro"),
    ("Conta Simples", "Financeiro"),
    ("BHub", "Financeiro"),
    ("Nibo", "Financeiro"),
    ("Omie", "Financeiro"),
    ("Contabilizei", "Financeiro"),
    ("Creditas", "Financeiro"),
    ("Geru", "Financeiro"),
    ("Open Co", "Financeiro"),
    ("Rebel", "Financeiro"),
    ("Just", "Financeiro"),
    ("Kavod Lending", "Financeiro"),
    ("Biva", "Financeiro"),
    ("Bcredi", "Financeiro"),
    ("Provu", "Financeiro"),
    ("Trigg", "Financeiro"),
    ("Méliuz", "Financeiro"),
    ("Mosaico", "Financeiro"),
    ("Bling", "Financeiro"),
    ("Conta Azul", "Financeiro"),
    ("Quero Quitar", "Financeiro"),
    ("Acordo Certo", "Financeiro"),
    ("Konkero", "Financeiro"),
    ("FinanZero", "Financeiro"),
    ("Wise", "Financeiro"),
    ("Remessa Online", "Financeiro"),
    ("Western Union", "Financeiro"),
    ("MoneyGram", "Financeiro"),
    ("Visa", "Financeiro"),
    ("Mastercard", "Financeiro"),
    ("American Express", "Financeiro"),
    ("Elo", "Financeiro"),
    ("Hipercard", "Financeiro"),
    ("XP Investimentos", "Financeiro"),
    ("XP Inc", "Financeiro"),
    ("Rico", "Financeiro"),
    ("Clear", "Financeiro"),
    ("Modal", "Financeiro"),
    ("Genial Investimentos", "Financeiro"),
    ("Toro Investimentos", "Financeiro"),
    ("Easynvest", "Financeiro"),
    ("Órama", "Financeiro"),
    ("Warren", "Financeiro"),
    ("Avenue", "Financeiro"),
    ("Empiricus", "Financeiro"),
    ("Suno Research", "Financeiro"),
    ("Spiti", "Financeiro"),
    ("Levante Ideias", "Financeiro"),
    ("StatusInvest", "Financeiro"),
    ("Capital Aberto", "Financeiro"),
    ("Wright Capital", "Financeiro"),
    ("Vinci Partners", "Financeiro"),
    ("Pátria Investimentos", "Financeiro"),
    ("Bozano Investimentos", "Financeiro"),
    ("ARX", "Financeiro"),
    ("SPX Capital", "Financeiro"),
    ("Verde Asset", "Financeiro"),
    ("Adam Capital", "Financeiro"),
    ("Kapitalo", "Financeiro"),
    ("Kinea", "Financeiro"),
    ("Garde", "Financeiro"),
    ("Ibiuna", "Financeiro"),
    ("Legacy Capital", "Financeiro"),
    ("Truxt", "Financeiro"),
    ("Constellation", "Financeiro"),
    ("Dynamo", "Financeiro"),
    ("Atmos Capital", "Financeiro"),
    ("Opportunity", "Financeiro"),
    ("Brasil Plural", "Financeiro"),
    ("BR Partners", "Financeiro"),
    ("Banco Plural", "Financeiro"),
    ("Itaú Asset", "Financeiro"),
    ("Bradesco Asset", "Financeiro"),
    ("BB Asset", "Financeiro"),
    ("Santander Asset", "Financeiro"),
    ("Caixa Asset", "Financeiro"),
    ("Brasilprev", "Financeiro"),
    ("Brasilcap", "Financeiro"),
    ("Icatu Seguros", "Financeiro"),
    ("Prudential do Brasil", "Financeiro"),
    ("MetLife Brasil", "Financeiro"),
    ("Liberty Seguros", "Financeiro"),
    ("Mapfre", "Financeiro"),
    ("Mapfre Seguros", "Financeiro"),
    ("Allianz", "Financeiro"),
    ("Allianz Seguros", "Financeiro"),
    ("Tokio Marine", "Financeiro"),
    ("Sompo Seguros", "Financeiro"),
    ("Zurich Brasil", "Financeiro"),
    ("HDI Seguros", "Financeiro"),
    ("Chubb", "Financeiro"),
    ("AIG", "Financeiro"),
    ("Marsh", "Financeiro"),
    ("Willis Towers Watson", "Financeiro"),
    ("Aon", "Financeiro"),
    ("Mongeral Aegon", "Financeiro"),
    ("Capemisa", "Financeiro"),
    ("Porto Seguro", "Financeiro"),
    ("Porto", "Financeiro"),
    ("SulAmérica", "Financeiro"),
    ("Bradesco Vida e Previdência", "Financeiro"),
    ("Caixa Seguridade", "Financeiro"),
    ("IRB Brasil RE", "Financeiro"),
    ("Wiz", "Financeiro"),
    ("Cordialli", "Financeiro"),
    ("BB Seguridade", "Financeiro"),
    ("Crefisa", "Financeiro"),
    ("Banco Olé", "Financeiro"),
    ("Banco Cetelem", "Financeiro"),
    ("Cetelem", "Financeiro"),
    ("Santander Consumer", "Financeiro"),
    ("Renner Card", "Financeiro"),
    ("Cred-System", "Financeiro"),

    # --- Tecnologia ---
    ("Totvs", "Tecnologia"),
    ("Linx", "Tecnologia"),
    ("Locaweb", "Tecnologia"),
    ("Sinqia", "Tecnologia"),
    ("Senior Sistemas", "Tecnologia"),
    ("Tivit", "Tecnologia"),
    ("Stefanini", "Tecnologia"),
    ("CI&T", "Tecnologia"),
    ("CIT", "Tecnologia"),
    ("Indra Brasil", "Tecnologia"),
    ("Capgemini", "Tecnologia"),
    ("Accenture", "Tecnologia"),
    ("Deloitte", "Tecnologia"),
    ("KPMG", "Tecnologia"),
    ("PwC", "Tecnologia"),
    ("EY", "Tecnologia"),
    ("Ernst Young", "Tecnologia"),
    ("BDO", "Tecnologia"),
    ("Grant Thornton", "Tecnologia"),
    ("Mazars", "Tecnologia"),
    ("RSM Brasil", "Tecnologia"),
    ("Atos", "Tecnologia"),
    ("DXC Technology", "Tecnologia"),
    ("Unisys", "Tecnologia"),
    ("Cognizant", "Tecnologia"),
    ("Wipro", "Tecnologia"),
    ("Infosys", "Tecnologia"),
    ("HCL Technologies", "Tecnologia"),
    ("Tata Consultancy Services", "Tecnologia"),
    ("TCS", "Tecnologia"),
    ("Microsoft Brasil", "Tecnologia"),
    ("Microsoft", "Tecnologia"),
    ("Google Brasil", "Tecnologia"),
    ("Google", "Tecnologia"),
    ("Amazon Brasil", "Tecnologia"),
    ("AWS", "Tecnologia"),
    ("Meta", "Tecnologia"),
    ("Facebook Brasil", "Tecnologia"),
    ("Apple Brasil", "Tecnologia"),
    ("Oracle Brasil", "Tecnologia"),
    ("Oracle", "Tecnologia"),
    ("SAP Brasil", "Tecnologia"),
    ("SAP", "Tecnologia"),
    ("IBM Brasil", "Tecnologia"),
    ("IBM", "Tecnologia"),
    ("Dell Brasil", "Tecnologia"),
    ("Dell", "Tecnologia"),
    ("HP Brasil", "Tecnologia"),
    ("HP Inc", "Tecnologia"),
    ("HPE", "Tecnologia"),
    ("Hewlett Packard Enterprise", "Tecnologia"),
    ("Cisco", "Tecnologia"),
    ("Cisco Brasil", "Tecnologia"),
    ("Intel Brasil", "Tecnologia"),
    ("AMD", "Tecnologia"),
    ("NVIDIA Brasil", "Tecnologia"),
    ("Lenovo", "Tecnologia"),
    ("Asus Brasil", "Tecnologia"),
    ("Positivo Tecnologia", "Tecnologia"),
    ("Multilaser", "Tecnologia"),
    ("Intelbras", "Tecnologia"),
    ("Salesforce", "Tecnologia"),
    ("ServiceNow", "Tecnologia"),
    ("Workday", "Tecnologia"),
    ("Atlassian", "Tecnologia"),
    ("Slack", "Tecnologia"),
    ("Zoom", "Tecnologia"),
    ("Adobe", "Tecnologia"),
    ("Autodesk", "Tecnologia"),
    ("VMware", "Tecnologia"),
    ("Red Hat", "Tecnologia"),
    ("Dynatrace", "Tecnologia"),
    ("Datadog", "Tecnologia"),
    ("New Relic", "Tecnologia"),
    ("Splunk", "Tecnologia"),
    ("Cloudflare", "Tecnologia"),
    ("Akamai", "Tecnologia"),
    ("F5 Networks", "Tecnologia"),
    ("Palo Alto Networks", "Tecnologia"),
    ("Fortinet", "Tecnologia"),
    ("CrowdStrike", "Tecnologia"),
    ("Sophos", "Tecnologia"),
    ("Trend Micro", "Tecnologia"),
    ("Kaspersky", "Tecnologia"),
    ("Symantec", "Tecnologia"),
    ("McAfee", "Tecnologia"),
    ("Tenable", "Tecnologia"),
    ("Rapid7", "Tecnologia"),
    ("Snowflake", "Tecnologia"),
    ("Databricks", "Tecnologia"),
    ("MongoDB", "Tecnologia"),
    ("Elastic", "Tecnologia"),
    ("Confluent", "Tecnologia"),
    ("HashiCorp", "Tecnologia"),
    ("GitLab", "Tecnologia"),
    ("GitHub", "Tecnologia"),
    ("Twilio", "Tecnologia"),
    ("Stripe", "Tecnologia"),
    ("Shopify", "Tecnologia"),
    ("Squarespace", "Tecnologia"),
    ("Canva", "Tecnologia"),
    ("Figma", "Tecnologia"),
    ("Notion", "Tecnologia"),
    ("Monday", "Tecnologia"),
    ("Asana", "Tecnologia"),
    ("Trello", "Tecnologia"),
    ("Pipedrive", "Tecnologia"),
    ("HubSpot", "Tecnologia"),
    ("Zendesk", "Tecnologia"),
    ("Freshworks", "Tecnologia"),
    ("Intercom", "Tecnologia"),
    ("RD Station", "Tecnologia"),
    ("Resultados Digitais", "Tecnologia"),
    ("Hotmart", "Tecnologia"),
    ("Eduzz", "Tecnologia"),
    ("Monetizze", "Tecnologia"),
    ("Kiwify", "Tecnologia"),
    ("Braip", "Tecnologia"),
    ("Movile", "Tecnologia"),
    ("iFood", "Tecnologia"),
    ("PlayKids", "Tecnologia"),
    ("Wildlife Studios", "Tecnologia"),
    ("Tapps Games", "Tecnologia"),
    ("Aquiris Game Studio", "Tecnologia"),
    ("Hoplon", "Tecnologia"),
    ("Loft", "Tecnologia"),
    ("Quinto Andar", "Tecnologia"),
    ("QuintoAndar", "Tecnologia"),
    ("EmCasa", "Tecnologia"),
    ("Loft Cred", "Tecnologia"),
    ("Olist", "Tecnologia"),
    ("MadeiraMadeira", "Tecnologia"),
    ("Madeira Madeira", "Tecnologia"),
    ("Westwing", "Tecnologia"),
    ("Mobly", "Tecnologia"),
    ("Dafiti", "Tecnologia"),
    ("Kanui", "Tecnologia"),
    ("Tricae", "Tecnologia"),
    ("Netshoes", "Tecnologia"),
    ("Privalia", "Tecnologia"),
    ("Submarino", "Tecnologia"),
    ("Shoptime", "Tecnologia"),
    ("Buscapé", "Tecnologia"),
    ("Zoom", "Tecnologia"),
    ("Mercado Livre", "Tecnologia"),
    ("MercadoLibre", "Tecnologia"),
    ("Mercado Envios", "Tecnologia"),
    ("Mercado Shops", "Tecnologia"),
    ("OLX", "Tecnologia"),
    ("Webmotors", "Tecnologia"),
    ("ZAP Imóveis", "Tecnologia"),
    ("ZapImoveis", "Tecnologia"),
    ("VivaReal", "Tecnologia"),
    ("Imovelweb", "Tecnologia"),
    ("Catho", "Tecnologia"),
    ("Vagas.com", "Tecnologia"),
    ("Infojobs", "Tecnologia"),
    ("LinkedIn Brasil", "Tecnologia"),
    ("Indeed Brasil", "Tecnologia"),
    ("Glassdoor", "Tecnologia"),
    ("Solides", "Tecnologia"),
    ("Gupy", "Tecnologia"),
    ("Kenoby", "Tecnologia"),
    ("InHire", "Tecnologia"),
    ("Vagas Tecnologia", "Tecnologia"),
    ("Sólides", "Tecnologia"),
    ("Convenia", "Tecnologia"),
    ("Sólides Tangerino", "Tecnologia"),
    ("Tangerino", "Tecnologia"),
    ("Pontotel", "Tecnologia"),
    ("Feedz", "Tecnologia"),
    ("Track.co", "Tecnologia"),
    ("Senior", "Tecnologia"),
    ("ADP Brasil", "Tecnologia"),
    ("LG Lugar de Gente", "Tecnologia"),
    ("Engesoftware", "Tecnologia"),
    ("Squadra", "Tecnologia"),
    ("Quality Digital", "Tecnologia"),
    ("Stoque", "Tecnologia"),
    ("DBA Engenharia", "Tecnologia"),
    ("BRQ", "Tecnologia"),
    ("Resource", "Tecnologia"),
    ("Sonda Brasil", "Tecnologia"),
    ("Politec", "Tecnologia"),
    ("CTIS Tecnologia", "Tecnologia"),
    ("Compasso UOL", "Tecnologia"),
    ("UOL", "Tecnologia"),
    ("UOL Edtech", "Tecnologia"),
    ("UOL HOST", "Tecnologia"),
    ("UOL Diveo", "Tecnologia"),
    ("PagSeguro UOL", "Tecnologia"),
    ("BoaVista Tecnologia", "Tecnologia"),
    ("Equifax", "Tecnologia"),
    ("Serasa Experian", "Tecnologia"),
    ("Serasa", "Tecnologia"),
    ("SPC Brasil", "Tecnologia"),
    ("Quod", "Tecnologia"),
    ("ClearSale", "Tecnologia"),
    ("Konduto", "Tecnologia"),
    ("Truora", "Tecnologia"),
    ("Idwall", "Tecnologia"),
    ("Unico", "Tecnologia"),
    ("Acesso Digital", "Tecnologia"),
    ("DocuSign", "Tecnologia"),
    ("ClickSign", "Tecnologia"),
    ("D4Sign", "Tecnologia"),
    ("ContaAzul", "Tecnologia"),
    ("Nibo", "Tecnologia"),
    ("Sage Brasil", "Tecnologia"),
    ("Domínio Sistemas", "Tecnologia"),
    ("Alterdata", "Tecnologia"),
    ("Sankhya", "Tecnologia"),
    ("BENNER", "Tecnologia"),
    ("Mega Sistemas", "Tecnologia"),
    ("Compass UOL", "Tecnologia"),
    ("Globant", "Tecnologia"),
    ("Endava", "Tecnologia"),
    ("Encora", "Tecnologia"),
    ("ThoughtWorks", "Tecnologia"),
    ("Thoughtworks", "Tecnologia"),
    ("EPAM", "Tecnologia"),
    ("Pessoa Tech", "Tecnologia"),
    ("Concrete", "Tecnologia"),
    ("Concrete Solutions", "Tecnologia"),
    ("DTI Digital", "Tecnologia"),
    ("Codeminer42", "Tecnologia"),
    ("Plataformatec", "Tecnologia"),
    ("Pagaleve", "Tecnologia"),
    ("Adyen", "Tecnologia"),
    ("Worldpay", "Tecnologia"),
    ("Ebanx", "Tecnologia"),
    ("Stark Bank", "Tecnologia"),
    ("Dock", "Tecnologia"),
    ("Pismo", "Tecnologia"),
    ("Conductor", "Tecnologia"),
    ("Movile Pay", "Tecnologia"),
    ("Zoop", "Tecnologia"),
    ("Vindi", "Tecnologia"),
    ("Pagar.me", "Tecnologia"),
    ("PagarMe", "Tecnologia"),
    ("Asaas", "Tecnologia"),

    # --- Varejo e Consumo ---
    ("Magazine Luiza", "Varejo e Consumo"),
    ("Magalu", "Varejo e Consumo"),
    ("Casas Bahia", "Varejo e Consumo"),
    ("Grupo Casas Bahia", "Varejo e Consumo"),
    ("Via", "Varejo e Consumo"),
    ("Via Varejo", "Varejo e Consumo"),
    ("Lojas Americanas", "Varejo e Consumo"),
    ("Americanas", "Varejo e Consumo"),
    ("Submarino", "Varejo e Consumo"),
    ("Shoptime", "Varejo e Consumo"),
    ("Renner", "Varejo e Consumo"),
    ("Lojas Renner", "Varejo e Consumo"),
    ("Riachuelo", "Varejo e Consumo"),
    ("Lojas Riachuelo", "Varejo e Consumo"),
    ("C&A", "Varejo e Consumo"),
    ("Marisa", "Varejo e Consumo"),
    ("Lojas Marisa", "Varejo e Consumo"),
    ("Pernambucanas", "Varejo e Consumo"),
    ("Havan", "Varejo e Consumo"),
    ("Centauro", "Varejo e Consumo"),
    ("Decathlon", "Varejo e Consumo"),
    ("Netshoes", "Varejo e Consumo"),
    ("Kabum", "Varejo e Consumo"),
    ("KaBuM", "Varejo e Consumo"),
    ("Polishop", "Varejo e Consumo"),
    ("Fast Shop", "Varejo e Consumo"),
    ("Ricardo Eletro", "Varejo e Consumo"),
    ("Insinuante", "Varejo e Consumo"),
    ("Lojas Quero Quero", "Varejo e Consumo"),
    ("Quero Quero", "Varejo e Consumo"),
    ("Lojas Cem", "Varejo e Consumo"),
    ("Colombo", "Varejo e Consumo"),
    ("Lojas Colombo", "Varejo e Consumo"),
    ("Tok Stok", "Varejo e Consumo"),
    ("Tok&Stok", "Varejo e Consumo"),
    ("Etna", "Varejo e Consumo"),
    ("Camicado", "Varejo e Consumo"),
    ("Le Biscuit", "Varejo e Consumo"),
    ("Lebes", "Varejo e Consumo"),
    ("Lojas Lebes", "Varejo e Consumo"),
    ("Casa & Video", "Varejo e Consumo"),
    ("Lojas Becker", "Varejo e Consumo"),
    ("Hering", "Varejo e Consumo"),
    ("Lojas Hering", "Varejo e Consumo"),
    ("Track&Field", "Varejo e Consumo"),
    ("Track Field", "Varejo e Consumo"),
    ("Hering Store", "Varejo e Consumo"),
    ("Malwee", "Varejo e Consumo"),
    ("Pucket", "Varejo e Consumo"),
    ("Marisol", "Varejo e Consumo"),
    ("Lupo", "Varejo e Consumo"),
    ("Trifil", "Varejo e Consumo"),
    ("Scalina", "Varejo e Consumo"),
    ("De Millus", "Varejo e Consumo"),
    ("Liz", "Varejo e Consumo"),
    ("Hope Lingerie", "Varejo e Consumo"),
    ("Valisere", "Varejo e Consumo"),
    ("Loungerie", "Varejo e Consumo"),
    ("Calvin Klein Brasil", "Varejo e Consumo"),
    ("Forever 21", "Varejo e Consumo"),
    ("Zara Brasil", "Varejo e Consumo"),
    ("H&M Brasil", "Varejo e Consumo"),
    ("Levi's Brasil", "Varejo e Consumo"),
    ("Lacoste Brasil", "Varejo e Consumo"),
    ("Nike Brasil", "Varejo e Consumo"),
    ("Adidas Brasil", "Varejo e Consumo"),
    ("Puma Brasil", "Varejo e Consumo"),
    ("New Balance", "Varejo e Consumo"),
    ("Under Armour", "Varejo e Consumo"),
    ("Mizuno", "Varejo e Consumo"),
    ("Asics", "Varejo e Consumo"),
    ("Olympikus", "Varejo e Consumo"),
    ("Vulcabras", "Varejo e Consumo"),
    ("Grendene", "Varejo e Consumo"),
    ("Melissa", "Varejo e Consumo"),
    ("Beira Rio", "Varejo e Consumo"),
    ("Bibi", "Varejo e Consumo"),
    ("Klin", "Varejo e Consumo"),
    ("Pampili", "Varejo e Consumo"),
    ("Kidy", "Varejo e Consumo"),
    ("Ortopé", "Varejo e Consumo"),
    ("Schutz", "Varejo e Consumo"),
    ("Arezzo&Co", "Varejo e Consumo"),
    ("Anacapri", "Varejo e Consumo"),
    ("Vans Brasil", "Varejo e Consumo"),
    ("Reserva", "Varejo e Consumo"),
    ("Osklen", "Varejo e Consumo"),
    ("Animale", "Varejo e Consumo"),
    ("Farm", "Varejo e Consumo"),
    ("Farm Rio", "Varejo e Consumo"),
    ("Cantão", "Varejo e Consumo"),
    ("Maria Filó", "Varejo e Consumo"),
    ("NK Store", "Varejo e Consumo"),
    ("Le Lis Blanc", "Varejo e Consumo"),
    ("Restoque", "Varejo e Consumo"),
    ("Rosa Chá", "Varejo e Consumo"),
    ("Cia Marítima", "Varejo e Consumo"),
    ("Lenny Niemeyer", "Varejo e Consumo"),
    ("Bo.Bô", "Varejo e Consumo"),
    ("Carmim", "Varejo e Consumo"),
    ("MOB", "Varejo e Consumo"),
    ("Iódice", "Varejo e Consumo"),
    ("Espaço Fashion", "Varejo e Consumo"),
    ("M.Officer", "Varejo e Consumo"),
    ("Forum", "Varejo e Consumo"),
    ("Ellus", "Varejo e Consumo"),
    ("Pólo Wear", "Varejo e Consumo"),
    ("Polo Wear", "Varejo e Consumo"),
    ("VR Menswear", "Varejo e Consumo"),
    ("Aramis", "Varejo e Consumo"),
    ("Hugo Boss Brasil", "Varejo e Consumo"),
    ("Boticário", "Varejo e Consumo"),
    ("O Boticário", "Varejo e Consumo"),
    ("Grupo Boticário", "Varejo e Consumo"),
    ("Eudora", "Varejo e Consumo"),
    ("Quem Disse Berenice", "Varejo e Consumo"),
    ("Natura", "Varejo e Consumo"),
    ("Avon", "Varejo e Consumo"),
    ("Natura Cosméticos", "Varejo e Consumo"),
    ("Granado", "Varejo e Consumo"),
    ("Phebo", "Varejo e Consumo"),
    ("L'Oréal Brasil", "Varejo e Consumo"),
    ("L'Oréal", "Varejo e Consumo"),
    ("Loreal", "Varejo e Consumo"),
    ("Unilever Brasil", "Varejo e Consumo"),
    ("Unilever", "Varejo e Consumo"),
    ("P&G", "Varejo e Consumo"),
    ("Procter Gamble", "Varejo e Consumo"),
    ("Procter & Gamble", "Varejo e Consumo"),
    ("Johnson Johnson", "Varejo e Consumo"),
    ("Johnson & Johnson", "Varejo e Consumo"),
    ("Colgate Palmolive", "Varejo e Consumo"),
    ("Colgate", "Varejo e Consumo"),
    ("Reckitt Benckiser", "Varejo e Consumo"),
    ("Reckitt", "Varejo e Consumo"),
    ("Bombril", "Varejo e Consumo"),
    ("Bombril Brasil", "Varejo e Consumo"),
    ("Ypê", "Varejo e Consumo"),
    ("Sara Lee Brasil", "Varejo e Consumo"),
    ("Beiersdorf", "Varejo e Consumo"),
    ("Henkel", "Varejo e Consumo"),
    ("Estée Lauder Brasil", "Varejo e Consumo"),
    ("Estee Lauder", "Varejo e Consumo"),
    ("LVMH Brasil", "Varejo e Consumo"),
    ("Sephora", "Varejo e Consumo"),
    ("Mac Cosmetics", "Varejo e Consumo"),
    ("Coca-Cola FEMSA", "Varejo e Consumo"),
    ("Coca-Cola Brasil", "Varejo e Consumo"),
    ("Coca Cola", "Varejo e Consumo"),
    ("PepsiCo Brasil", "Varejo e Consumo"),
    ("PepsiCo", "Varejo e Consumo"),
    ("AmBev", "Varejo e Consumo"),
    ("Heineken Brasil", "Varejo e Consumo"),
    ("Heineken", "Varejo e Consumo"),
    ("Petrópolis", "Varejo e Consumo"),
    ("Grupo Petrópolis", "Varejo e Consumo"),
    ("Cervejaria Petrópolis", "Varejo e Consumo"),
    ("Brasil Kirin", "Varejo e Consumo"),
    ("Schincariol", "Varejo e Consumo"),
    ("Itaipava", "Varejo e Consumo"),
    ("Devassa", "Varejo e Consumo"),
    ("Eisenbahn", "Varejo e Consumo"),
    ("Coca Cola Andina", "Varejo e Consumo"),
    ("Coca Cola Solar", "Varejo e Consumo"),
    ("Itaúsa", "Varejo e Consumo"),

    # --- Indústria ---
    ("Vale", "Indústria"),
    ("CSN", "Indústria"),
    ("Gerdau", "Indústria"),
    ("Usiminas", "Indústria"),
    ("ArcelorMittal Brasil", "Indústria"),
    ("ArcelorMittal", "Indústria"),
    ("Aperam South America", "Indústria"),
    ("Aperam", "Indústria"),
    ("Ternium Brasil", "Indústria"),
    ("Ferbasa", "Indústria"),
    ("Mangels", "Indústria"),
    ("Paranapanema", "Indústria"),
    ("Caraíba Metais", "Indústria"),
    ("Votorantim", "Indústria"),
    ("Votorantim Cimentos", "Indústria"),
    ("InterCement", "Indústria"),
    ("Cimento Tupi", "Indústria"),
    ("Cimento Itambé", "Indústria"),
    ("Holcim Brasil", "Indústria"),
    ("LafargeHolcim", "Indústria"),
    ("Eternit", "Indústria"),
    ("Brasilit", "Indústria"),
    ("Saint-Gobain", "Indústria"),
    ("Saint Gobain", "Indústria"),
    ("Owens Corning", "Indústria"),
    ("Knauf", "Indústria"),
    ("Roca Brasil", "Indústria"),
    ("Deca", "Indústria"),
    ("Duratex", "Indústria"),
    ("Dexco", "Indústria"),
    ("Tigre", "Indústria"),
    ("Amanco", "Indústria"),
    ("Tramontina", "Indústria"),
    ("Brastemp", "Indústria"),
    ("Consul", "Indústria"),
    ("Whirlpool Brasil", "Indústria"),
    ("Whirlpool", "Indústria"),
    ("Electrolux Brasil", "Indústria"),
    ("Electrolux", "Indústria"),
    ("Mabe", "Indústria"),
    ("Mueller Eletrodomésticos", "Indústria"),
    ("Esmaltec", "Indústria"),
    ("Britânia", "Indústria"),
    ("Philco", "Indústria"),
    ("Mondial", "Indústria"),
    ("Cadence", "Indústria"),
    ("Arno", "Indústria"),
    ("Black & Decker Brasil", "Indústria"),
    ("Stanley Black Decker", "Indústria"),
    ("Bosch Brasil", "Indústria"),
    ("Bosch", "Indústria"),
    ("Siemens Brasil", "Indústria"),
    ("Siemens", "Indústria"),
    ("ABB Brasil", "Indústria"),
    ("ABB", "Indústria"),
    ("Schneider Electric Brasil", "Indústria"),
    ("Schneider Electric", "Indústria"),
    ("WEG", "Indústria"),
    ("Romi", "Indústria"),
    ("Indústrias Romi", "Indústria"),
    ("Marcopolo", "Indústria"),
    ("Iochpe-Maxion", "Indústria"),
    ("Iochpe Maxion", "Indústria"),
    ("Randon", "Indústria"),
    ("Randoncorp", "Indústria"),
    ("Embraer", "Indústria"),
    ("Eve Air Mobility", "Indústria"),
    ("Helibras", "Indústria"),
    ("AEL Sistemas", "Indústria"),
    ("Akaer", "Indústria"),
    ("Atech", "Indústria"),
    ("Inbra Aerospace", "Indústria"),
    ("Avibras", "Indústria"),
    ("Mercedes-Benz Brasil", "Indústria"),
    ("Mercedes Benz", "Indústria"),
    ("Volkswagen Brasil", "Indústria"),
    ("Volkswagen Caminhões", "Indústria"),
    ("Scania Brasil", "Indústria"),
    ("Scania", "Indústria"),
    ("Volvo Brasil", "Indústria"),
    ("Volvo", "Indústria"),
    ("MAN Latin America", "Indústria"),
    ("Iveco", "Indústria"),
    ("Stellantis", "Indústria"),
    ("Fiat", "Indústria"),
    ("Jeep", "Indústria"),
    ("Peugeot Citroën", "Indústria"),
    ("Renault Brasil", "Indústria"),
    ("Renault", "Indústria"),
    ("Nissan Brasil", "Indústria"),
    ("Nissan", "Indústria"),
    ("Toyota Brasil", "Indústria"),
    ("Toyota", "Indústria"),
    ("Honda Brasil", "Indústria"),
    ("Honda", "Indústria"),
    ("Hyundai Brasil", "Indústria"),
    ("Hyundai", "Indústria"),
    ("Kia Motors", "Indústria"),
    ("BMW Brasil", "Indústria"),
    ("BMW", "Indústria"),
    ("Audi Brasil", "Indústria"),
    ("Audi", "Indústria"),
    ("Caoa", "Indústria"),
    ("Caoa Chery", "Indústria"),
    ("GWM Brasil", "Indústria"),
    ("BYD Brasil", "Indústria"),
    ("BYD", "Indústria"),
    ("Foxconn Brasil", "Indústria"),
    ("Flex Brasil", "Indústria"),
    ("Jabil Brasil", "Indústria"),
    ("Sanmina", "Indústria"),
    ("Magneti Marelli", "Indústria"),
    ("Magneti", "Indústria"),
    ("Bosch Rexroth", "Indústria"),
    ("Continental Brasil", "Indústria"),
    ("ZF do Brasil", "Indústria"),
    ("Mahle", "Indústria"),
    ("Eaton", "Indústria"),
    ("Pirelli Brasil", "Indústria"),
    ("Pirelli", "Indústria"),
    ("Goodyear Brasil", "Indústria"),
    ("Goodyear", "Indústria"),
    ("Michelin", "Indústria"),
    ("Bridgestone Brasil", "Indústria"),
    ("Bridgestone", "Indústria"),
    ("Continental Pneus", "Indústria"),
    ("Klabin", "Indústria"),
    ("Suzano", "Indústria"),
    ("Fibria", "Indústria"),
    ("Eldorado Brasil", "Indústria"),
    ("Bracell", "Indústria"),
    ("CMPC", "Indústria"),
    ("Irani", "Indústria"),
    ("Sonae Sierra Brasil", "Indústria"),
    ("Mondi", "Indústria"),
    ("International Paper Brasil", "Indústria"),
    ("Stora Enso", "Indústria"),
    ("Sylvamo", "Indústria"),
    ("Riopelle", "Indústria"),
    ("Smurfit Kappa", "Indústria"),
    ("Vidraria Anchieta", "Indústria"),
    ("Owens Illinois", "Indústria"),
    ("Wheaton Brasil", "Indústria"),
    ("Verallia", "Indústria"),
    ("Saint-Gobain Vidros", "Indústria"),
    ("Cebrace", "Indústria"),
    ("Guardian Industries", "Indústria"),
    ("Vivix Vidros", "Indústria"),
    ("AGC Brasil", "Indústria"),
    ("Bayer Brasil", "Indústria"),
    ("Bayer", "Indústria"),
    ("BASF Brasil", "Indústria"),
    ("BASF", "Indústria"),
    ("Dow Brasil", "Indústria"),
    ("Dow", "Indústria"),
    ("DuPont Brasil", "Indústria"),
    ("DuPont", "Indústria"),
    ("Braskem", "Indústria"),
    ("Petrocoque", "Indústria"),
    ("Unipar", "Indústria"),
    ("Solvay", "Indústria"),
    ("Lanxess", "Indústria"),
    ("Clariant", "Indústria"),
    ("Evonik", "Indústria"),
    ("Arkema", "Indústria"),
    ("AkzoNobel", "Indústria"),
    ("Sherwin-Williams", "Indústria"),
    ("Sherwin Williams", "Indústria"),
    ("PPG", "Indústria"),
    ("Tintas Coral", "Indústria"),
    ("Suvinil", "Indústria"),
    ("Polidura", "Indústria"),
    ("Renner Sayerlack", "Indústria"),
    ("Anjo Tintas", "Indústria"),

    # --- Saúde ---
    ("Hapvida", "Saúde"),
    ("NotreDame Intermédica", "Saúde"),
    ("Hapvida NotreDame Intermédica", "Saúde"),
    ("Rede D'Or", "Saúde"),
    ("Rede DOR", "Saúde"),
    ("Rede D Or", "Saúde"),
    ("Fleury", "Saúde"),
    ("Grupo Fleury", "Saúde"),
    ("Dasa", "Saúde"),
    ("Diagnósticos da América", "Saúde"),
    ("Hermes Pardini", "Saúde"),
    ("Alliar", "Saúde"),
    ("Amil", "Saúde"),
    ("Unimed", "Saúde"),
    ("Unimed Brasil", "Saúde"),
    ("Prevent Senior", "Saúde"),
    ("Allcare", "Saúde"),
    ("Cassi", "Saúde"),
    ("Geap", "Saúde"),
    ("Hospital Albert Einstein", "Saúde"),
    ("Hospital Sírio-Libanês", "Saúde"),
    ("Sírio Libanês", "Saúde"),
    ("Sírio-Libanês", "Saúde"),
    ("Hospital Oswaldo Cruz", "Saúde"),
    ("Hospital Samaritano", "Saúde"),
    ("Hospital 9 de Julho", "Saúde"),
    ("Hospital São Luiz", "Saúde"),
    ("Hospital Pro-Matre", "Saúde"),
    ("Hospital Santa Catarina", "Saúde"),
    ("Hospital Beneficência Portuguesa", "Saúde"),
    ("Beneficência Portuguesa", "Saúde"),
    ("Hospital São Camilo", "Saúde"),
    ("Hospital São Camilo Pompeia", "Saúde"),
    ("Hospital Santa Helena", "Saúde"),
    ("Hospital Vila Nova Star", "Saúde"),
    ("Hospital Moinhos de Vento", "Saúde"),
    ("Hospital de Clínicas de Porto Alegre", "Saúde"),
    ("Hospital Mãe de Deus", "Saúde"),
    ("Hospital Pequeno Príncipe", "Saúde"),
    ("Hospital Marcelino Champagnat", "Saúde"),
    ("Hospital Nossa Senhora das Graças", "Saúde"),
    ("Erasto Gaertner", "Saúde"),
    ("Hospital Erasto Gaertner", "Saúde"),
    ("Hospital Pilar", "Saúde"),
    ("Hospital Cardiológico Costantini", "Saúde"),
    ("Hospital Vita Curitiba", "Saúde"),
    ("Hospital São Vicente", "Saúde"),
    ("Hospital Esperança", "Saúde"),
    ("Real Hospital Português", "Saúde"),
    ("Hospital Memorial São José", "Saúde"),
    ("Hospital Santa Joana", "Saúde"),
    ("Hospital Procordis", "Saúde"),
    ("Hospital Quinta D'Or", "Saúde"),
    ("Hospital São Lucas", "Saúde"),
    ("Hospital Mater Dei", "Saúde"),
    ("Mater Dei", "Saúde"),
    ("Rede Mater Dei", "Saúde"),
    ("Hospital Vera Cruz", "Saúde"),
    ("Hospital Felício Rocho", "Saúde"),
    ("Hospital Madre Teresa", "Saúde"),
    ("Hospital Lifecenter", "Saúde"),
    ("Hospital Israelita", "Saúde"),
    ("Hospital Memorial DOR", "Saúde"),
    ("Hospital Vivalle", "Saúde"),
    ("Roche Brasil", "Saúde"),
    ("Roche", "Saúde"),
    ("Pfizer Brasil", "Saúde"),
    ("Pfizer", "Saúde"),
    ("Novartis Brasil", "Saúde"),
    ("Novartis", "Saúde"),
    ("Sanofi Brasil", "Saúde"),
    ("Sanofi", "Saúde"),
    ("GSK", "Saúde"),
    ("GlaxoSmithKline", "Saúde"),
    ("AstraZeneca Brasil", "Saúde"),
    ("AstraZeneca", "Saúde"),
    ("Merck Brasil", "Saúde"),
    ("Merck", "Saúde"),
    ("MSD Brasil", "Saúde"),
    ("MSD", "Saúde"),
    ("Abbott Brasil", "Saúde"),
    ("Abbott", "Saúde"),
    ("Bristol Myers Squibb", "Saúde"),
    ("BMS", "Saúde"),
    ("Boehringer Ingelheim", "Saúde"),
    ("Eli Lilly", "Saúde"),
    ("Takeda Brasil", "Saúde"),
    ("Takeda", "Saúde"),
    ("Novo Nordisk", "Saúde"),
    ("Astellas", "Saúde"),
    ("Daiichi Sankyo", "Saúde"),
    ("Servier", "Saúde"),
    ("Lundbeck", "Saúde"),
    ("Chiesi", "Saúde"),
    ("Menarini", "Saúde"),
    ("IPSEN", "Saúde"),
    ("UCB", "Saúde"),
    ("BIAL", "Saúde"),
    ("Mantecorp", "Saúde"),
    ("Medley", "Saúde"),
    ("Aché", "Saúde"),
    ("Ache Laboratorios", "Saúde"),
    ("Eurofarma", "Saúde"),
    ("EMS", "Saúde"),
    ("União Química", "Saúde"),
    ("Cristália", "Saúde"),
    ("Hypera Pharma", "Saúde"),
    ("Hypera", "Saúde"),
    ("Biolab", "Saúde"),
    ("Apsen", "Saúde"),
    ("Libbs", "Saúde"),
    ("Cimed", "Saúde"),
    ("Prati Donaduzzi", "Saúde"),
    ("Geolab", "Saúde"),
    ("Sandoz", "Saúde"),
    ("Aspen Pharma", "Saúde"),
    ("Aspen", "Saúde"),
    ("Cosmed", "Saúde"),
    ("Mantecorp Farmasa", "Saúde"),
    ("Brainfarma", "Saúde"),
    ("Neo Química", "Saúde"),
    ("Cellera Farma", "Saúde"),
    ("Galena", "Saúde"),
    ("Drogasil", "Saúde"),
    ("Droga Raia", "Saúde"),
    ("Raia Drogasil", "Saúde"),
    ("Pague Menos", "Saúde"),
    ("Drogarias Pacheco", "Saúde"),
    ("Drogaria São Paulo", "Saúde"),
    ("Onofre", "Saúde"),
    ("Panvel", "Saúde"),
    ("Drogarias Nissei", "Saúde"),
    ("Nissei", "Saúde"),
    ("Big Ben", "Saúde"),
    ("Drogaria Araujo", "Saúde"),
    ("Araujo", "Saúde"),
    ("Drogal", "Saúde"),
    ("Drogarias Tamoio", "Saúde"),
    ("Farmácia Indiana", "Saúde"),
    ("Farmácia Permanente", "Saúde"),
    ("Drogamed", "Saúde"),
    ("Profarma", "Saúde"),
    ("Tempo Assist", "Saúde"),
    ("Memed", "Saúde"),
    ("Doctoralia", "Saúde"),
    ("BoaConsulta", "Saúde"),
    ("Conexa Saúde", "Saúde"),
    ("Pebmed", "Saúde"),
    ("Whitebook", "Saúde"),
    ("iClinic", "Saúde"),
    ("Tasy", "Saúde"),
    ("MV Sistemas", "Saúde"),
    ("Wareline", "Saúde"),
    ("Pixeon", "Saúde"),
    ("Vitalk", "Saúde"),
    ("Zenklub", "Saúde"),
    ("Cuco Health", "Saúde"),
    ("Pluris Saúde", "Saúde"),
    ("Genoa Health", "Saúde"),

    # --- Educação ---
    ("Cogna", "Educação"),
    ("Cogna Educação", "Educação"),
    ("Yduqs", "Educação"),
    ("Ânima", "Educação"),
    ("Ânima Educação", "Educação"),
    ("Anima Educacao", "Educação"),
    ("Estácio", "Educação"),
    ("Universidade Estácio de Sá", "Educação"),
    ("Cruzeiro do Sul", "Educação"),
    ("Cruzeiro do Sul Educacional", "Educação"),
    ("Unicesumar", "Educação"),
    ("Vitru", "Educação"),
    ("Afya", "Educação"),
    ("Eleva", "Educação"),
    ("Eleva Educação", "Educação"),
    ("SAE Digital", "Educação"),
    ("Kroton", "Educação"),
    ("Pitágoras", "Educação"),
    ("Anhanguera", "Educação"),
    ("Uniderp", "Educação"),
    ("Unopar", "Educação"),
    ("Saraiva", "Educação"),
    ("Editora Saraiva", "Educação"),
    ("Editora Abril", "Educação"),
    ("Editora Sextante", "Educação"),
    ("Editora Globo", "Educação"),
    ("Editora Record", "Educação"),
    ("FTD Educação", "Educação"),
    ("Moderna", "Educação"),
    ("Ática", "Educação"),
    ("Scipione", "Educação"),
    ("Pearson Brasil", "Educação"),
    ("Pearson", "Educação"),
    ("McGraw Hill Brasil", "Educação"),
    ("Cengage Brasil", "Educação"),
    ("Wiley Brasil", "Educação"),
    ("Springer Nature", "Educação"),
    ("Elsevier", "Educação"),
    ("Insper", "Educação"),
    ("FGV", "Educação"),
    ("Fundação Getulio Vargas", "Educação"),
    ("Ibmec", "Educação"),
    ("ESPM", "Educação"),
    ("FIA", "Educação"),
    ("Saint Paul", "Educação"),
    ("Conquer", "Educação"),
    ("Descomplica", "Educação"),
    ("AppProva", "Educação"),
    ("Geekie", "Educação"),
    ("Stoodi", "Educação"),
    ("ProEnem", "Educação"),
    ("Me Salva", "Educação"),
    ("Plataforma 9", "Educação"),
    ("Plataforma Mei", "Educação"),
    ("Wizard", "Educação"),
    ("Wise Up", "Educação"),
    ("CCAA", "Educação"),
    ("Cultura Inglesa", "Educação"),
    ("Yázigi", "Educação"),
    ("Fisk", "Educação"),
    ("Kumon", "Educação"),
    ("Alura", "Educação"),
    ("Trybe", "Educação"),
    ("Rocketseat", "Educação"),
    ("Digital Innovation One", "Educação"),
    ("DIO", "Educação"),
    ("Kenzie Academy", "Educação"),
    ("Reprograma", "Educação"),
    ("PrograMaria", "Educação"),
    ("Cubos Academy", "Educação"),
    ("Tera", "Educação"),
    ("PM3", "Educação"),
    ("Cursos PM3", "Educação"),
    ("Mentorama", "Educação"),
    ("Coursera", "Educação"),
    ("Udemy", "Educação"),
    ("EdX", "Educação"),
    ("Khan Academy", "Educação"),
    ("Duolingo", "Educação"),
    ("Babbel", "Educação"),
    ("Busuu", "Educação"),
    ("Open English", "Educação"),
    ("EF Education First", "Educação"),
    ("Maple Bear", "Educação"),
    ("Sistema COC", "Educação"),
    ("Bernoulli", "Educação"),
    ("Poliedro", "Educação"),
    ("Anglo", "Educação"),
    ("Etapa", "Educação"),
    ("Objetivo", "Educação"),
    ("Cursinho da Poli", "Educação"),
    ("CPV Educacional", "Educação"),
    ("Oficina do Estudante", "Educação"),
    ("Colégio Bandeirantes", "Educação"),
    ("Colégio Móbile", "Educação"),
    ("Colégio Dante Alighieri", "Educação"),
    ("Colégio Vértice", "Educação"),
    ("Colégio Etapa", "Educação"),

    # --- Energia e Utilities ---
    ("Petrobras", "Energia e Utilities"),
    ("Eletrobras", "Energia e Utilities"),
    ("Equatorial Energia", "Energia e Utilities"),
    ("Equatorial", "Energia e Utilities"),
    ("Energisa", "Energia e Utilities"),
    ("EDP Brasil", "Energia e Utilities"),
    ("EDP", "Energia e Utilities"),
    ("Engie Brasil", "Energia e Utilities"),
    ("Engie", "Energia e Utilities"),
    ("Enel Brasil", "Energia e Utilities"),
    ("Enel", "Energia e Utilities"),
    ("AES Brasil", "Energia e Utilities"),
    ("Cemig", "Energia e Utilities"),
    ("Copel", "Energia e Utilities"),
    ("Light", "Energia e Utilities"),
    ("Neoenergia", "Energia e Utilities"),
    ("Iberdrola", "Energia e Utilities"),
    ("Celesc", "Energia e Utilities"),
    ("CPFL Energia", "Energia e Utilities"),
    ("CPFL", "Energia e Utilities"),
    ("Eneva", "Energia e Utilities"),
    ("Auren Energia", "Energia e Utilities"),
    ("Auren", "Energia e Utilities"),
    ("Omega Energia", "Energia e Utilities"),
    ("Casa dos Ventos", "Energia e Utilities"),
    ("Renova Energia", "Energia e Utilities"),
    ("ERG Brasil", "Energia e Utilities"),
    ("AES Tietê", "Energia e Utilities"),
    ("Statkraft Brasil", "Energia e Utilities"),
    ("Voltalia", "Energia e Utilities"),
    ("Acciona", "Energia e Utilities"),
    ("EDF Norte Fluminense", "Energia e Utilities"),
    ("Vibra Energia", "Energia e Utilities"),
    ("Vibra", "Energia e Utilities"),
    ("Ipiranga", "Energia e Utilities"),
    ("Raízen", "Energia e Utilities"),
    ("Cosan", "Energia e Utilities"),
    ("Ultrapar", "Energia e Utilities"),
    ("Ultragaz", "Energia e Utilities"),
    ("Comgás", "Energia e Utilities"),
    ("Compagas", "Energia e Utilities"),
    ("Gas Natural Fenosa", "Energia e Utilities"),
    ("Naturgy", "Energia e Utilities"),
    ("Galp Brasil", "Energia e Utilities"),
    ("Galp", "Energia e Utilities"),
    ("Shell Brasil", "Energia e Utilities"),
    ("Shell", "Energia e Utilities"),
    ("Total Energies Brasil", "Energia e Utilities"),
    ("TotalEnergies", "Energia e Utilities"),
    ("Equinor", "Energia e Utilities"),
    ("BP Brasil", "Energia e Utilities"),
    ("BP", "Energia e Utilities"),
    ("Chevron Brasil", "Energia e Utilities"),
    ("Chevron", "Energia e Utilities"),
    ("ExxonMobil Brasil", "Energia e Utilities"),
    ("ExxonMobil", "Energia e Utilities"),
    ("Karoon Energy", "Energia e Utilities"),
    ("PetroRio", "Energia e Utilities"),
    ("PRIO", "Energia e Utilities"),
    ("3R Petroleum", "Energia e Utilities"),
    ("Sabesp", "Energia e Utilities"),
    ("Sanepar", "Energia e Utilities"),
    ("Copasa", "Energia e Utilities"),
    ("Cedae", "Energia e Utilities"),
    ("Caesb", "Energia e Utilities"),
    ("Compesa", "Energia e Utilities"),
    ("Embasa", "Energia e Utilities"),
    ("Casan", "Energia e Utilities"),
    ("Iguá Saneamento", "Energia e Utilities"),
    ("Aegea", "Energia e Utilities"),
    ("BRK Ambiental", "Energia e Utilities"),
    ("BRK", "Energia e Utilities"),
    ("Águas do Brasil", "Energia e Utilities"),
    ("GS Inima", "Energia e Utilities"),
    ("Ambipar", "Energia e Utilities"),
    ("Solvi", "Energia e Utilities"),
    ("Estre Ambiental", "Energia e Utilities"),
    ("Foxx", "Energia e Utilities"),
    ("Orizon", "Energia e Utilities"),
    ("Orizon Valorização", "Energia e Utilities"),
    ("Iguatemi", "Energia e Utilities"),
    ("Algar Telecom", "Energia e Utilities"),
    ("Telefônica Brasil", "Energia e Utilities"),
    ("Vivo", "Energia e Utilities"),
    ("Claro", "Energia e Utilities"),
    ("TIM", "Energia e Utilities"),
    ("Oi", "Energia e Utilities"),
    ("V.tal", "Energia e Utilities"),
    ("Vtal", "Energia e Utilities"),
    ("Brisanet", "Energia e Utilities"),
    ("Desktop", "Energia e Utilities"),
    ("Unifique", "Energia e Utilities"),
    ("Vero Internet", "Energia e Utilities"),
    ("Sercomtel", "Energia e Utilities"),
    ("Copel Telecom", "Energia e Utilities"),

    # --- Logística e Mobilidade ---
    ("Localiza", "Logística e Mobilidade"),
    ("Movida", "Logística e Mobilidade"),
    ("Unidas", "Logística e Mobilidade"),
    ("Vamos", "Logística e Mobilidade"),
    ("JSL", "Logística e Mobilidade"),
    ("Simpar", "Logística e Mobilidade"),
    ("CCR", "Logística e Mobilidade"),
    ("CCR Rodovias", "Logística e Mobilidade"),
    ("Ecorodovias", "Logística e Mobilidade"),
    ("EcoRodovias", "Logística e Mobilidade"),
    ("Arteris", "Logística e Mobilidade"),
    ("Rumo", "Logística e Mobilidade"),
    ("Rumo Logística", "Logística e Mobilidade"),
    ("MRS Logística", "Logística e Mobilidade"),
    ("MRS", "Logística e Mobilidade"),
    ("VLI", "Logística e Mobilidade"),
    ("VLI Logística", "Logística e Mobilidade"),
    ("Hidrovias do Brasil", "Logística e Mobilidade"),
    ("Wilson Sons", "Logística e Mobilidade"),
    ("Santos Brasil", "Logística e Mobilidade"),
    ("Tegma", "Logística e Mobilidade"),
    ("Sequoia Logística", "Logística e Mobilidade"),
    ("Sequoia", "Logística e Mobilidade"),
    ("Total Express", "Logística e Mobilidade"),
    ("Loggi", "Logística e Mobilidade"),
    ("Rappi", "Logística e Mobilidade"),
    ("99", "Logística e Mobilidade"),
    ("Uber", "Logística e Mobilidade"),
    ("Cabify", "Logística e Mobilidade"),
    ("inDriver", "Logística e Mobilidade"),
    ("Buser", "Logística e Mobilidade"),
    ("FlixBus", "Logística e Mobilidade"),
    ("Latam Airlines", "Logística e Mobilidade"),
    ("LATAM", "Logística e Mobilidade"),
    ("Gol Linhas Aéreas", "Logística e Mobilidade"),
    ("GOL", "Logística e Mobilidade"),
    ("Azul Linhas Aéreas", "Logística e Mobilidade"),
    ("Azul", "Logística e Mobilidade"),
    ("Voepass", "Logística e Mobilidade"),
    ("ITA Transportes Aéreos", "Logística e Mobilidade"),
    ("MAP Linhas Aéreas", "Logística e Mobilidade"),
    ("Airbus Brasil", "Logística e Mobilidade"),
    ("Boeing Brasil", "Logística e Mobilidade"),
    ("CCR Aeroportos", "Logística e Mobilidade"),
    ("AENA Brasil", "Logística e Mobilidade"),
    ("GRU Airport", "Logística e Mobilidade"),
    ("Infraero", "Logística e Mobilidade"),
    ("ANAC", "Logística e Mobilidade"),
    ("DHL Brasil", "Logística e Mobilidade"),
    ("DHL", "Logística e Mobilidade"),
    ("FedEx Brasil", "Logística e Mobilidade"),
    ("FedEx", "Logística e Mobilidade"),
    ("UPS Brasil", "Logística e Mobilidade"),
    ("UPS", "Logística e Mobilidade"),
    ("Correios", "Logística e Mobilidade"),
    ("Jadlog", "Logística e Mobilidade"),
    ("Mercado Envios", "Logística e Mobilidade"),
    ("Kuehne Nagel", "Logística e Mobilidade"),
    ("DB Schenker", "Logística e Mobilidade"),
    ("Geodis", "Logística e Mobilidade"),
    ("Mainfreight", "Logística e Mobilidade"),
    ("CEVA Logistics", "Logística e Mobilidade"),
    ("XPO Logistics", "Logística e Mobilidade"),
    ("GLP Brasil", "Logística e Mobilidade"),
    ("Prologis", "Logística e Mobilidade"),
    ("LOG CP", "Logística e Mobilidade"),
    ("BRMA Logística", "Logística e Mobilidade"),
    ("Direcional Engenharia", "Construção e Imóveis"),
    ("ID Logistics", "Logística e Mobilidade"),
    ("Penske Logistics", "Logística e Mobilidade"),

    # --- Construção e Imóveis ---
    ("MRV", "Construção e Imóveis"),
    ("Cyrela", "Construção e Imóveis"),
    ("Cyrela Brazil Realty", "Construção e Imóveis"),
    ("Eztec", "Construção e Imóveis"),
    ("Even", "Construção e Imóveis"),
    ("Direcional", "Construção e Imóveis"),
    ("Tenda", "Construção e Imóveis"),
    ("Gafisa", "Construção e Imóveis"),
    ("PDG Realty", "Construção e Imóveis"),
    ("Trisul", "Construção e Imóveis"),
    ("Lavvi", "Construção e Imóveis"),
    ("Helbor", "Construção e Imóveis"),
    ("Mitre Realty", "Construção e Imóveis"),
    ("Plano & Plano", "Construção e Imóveis"),
    ("Rossi Residencial", "Construção e Imóveis"),
    ("Tecnisa", "Construção e Imóveis"),
    ("RNI", "Construção e Imóveis"),
    ("Moura Dubeux", "Construção e Imóveis"),
    ("Living", "Construção e Imóveis"),
    ("Mendes Júnior", "Construção e Imóveis"),
    ("OAS", "Construção e Imóveis"),
    ("Odebrecht", "Construção e Imóveis"),
    ("Novonor", "Construção e Imóveis"),
    ("Construtora Norberto Odebrecht", "Construção e Imóveis"),
    ("Camargo Corrêa", "Construção e Imóveis"),
    ("Andrade Gutierrez", "Construção e Imóveis"),
    ("Queiroz Galvão", "Construção e Imóveis"),
    ("Mendes Junior", "Construção e Imóveis"),
    ("Galvão Engenharia", "Construção e Imóveis"),
    ("Engevix", "Construção e Imóveis"),
    ("Construcap", "Construção e Imóveis"),
    ("Sanenge", "Construção e Imóveis"),
    ("BR Foods", "Agro e Alimentos"),
    ("Construtora Tenda", "Construção e Imóveis"),
    ("Iguatemi Empresa de Shopping Centers", "Construção e Imóveis"),
    ("BR Properties", "Construção e Imóveis"),
    ("BRMalls", "Construção e Imóveis"),
    ("Multiplan", "Construção e Imóveis"),
    ("Aliansce Sonae", "Construção e Imóveis"),
    ("Allos", "Construção e Imóveis"),
    ("LOG Commercial Properties", "Construção e Imóveis"),
    ("Camargo Correa Industrial", "Construção e Imóveis"),
    ("Cushman & Wakefield", "Construção e Imóveis"),
    ("CBRE", "Construção e Imóveis"),
    ("JLL", "Construção e Imóveis"),
    ("Colliers", "Construção e Imóveis"),
    ("Newmark", "Construção e Imóveis"),
    ("RE/MAX", "Construção e Imóveis"),
    ("Lopes Imóveis", "Construção e Imóveis"),
    ("Brasil Brokers", "Construção e Imóveis"),
    ("Apsa", "Construção e Imóveis"),
    ("Auxiliadora Predial", "Construção e Imóveis"),
    ("Coelho da Fonseca", "Construção e Imóveis"),

    # --- Mídia e Entretenimento ---
    ("Globo", "Mídia e Entretenimento"),
    ("Grupo Globo", "Mídia e Entretenimento"),
    ("TV Globo", "Mídia e Entretenimento"),
    ("Globoplay", "Mídia e Entretenimento"),
    ("SporTV", "Mídia e Entretenimento"),
    ("Multishow", "Mídia e Entretenimento"),
    ("GloboNews", "Mídia e Entretenimento"),
    ("Record", "Mídia e Entretenimento"),
    ("Record TV", "Mídia e Entretenimento"),
    ("RecordTV", "Mídia e Entretenimento"),
    ("SBT", "Mídia e Entretenimento"),
    ("Band", "Mídia e Entretenimento"),
    ("Bandeirantes", "Mídia e Entretenimento"),
    ("Grupo Bandeirantes", "Mídia e Entretenimento"),
    ("RedeTV!", "Mídia e Entretenimento"),
    ("RedeTV", "Mídia e Entretenimento"),
    ("CNN Brasil", "Mídia e Entretenimento"),
    ("BandNews", "Mídia e Entretenimento"),
    ("Jovem Pan", "Mídia e Entretenimento"),
    ("Rádio Bandeirantes", "Mídia e Entretenimento"),
    ("Rádio Globo", "Mídia e Entretenimento"),
    ("Rádio Mix", "Mídia e Entretenimento"),
    ("Kiss FM", "Mídia e Entretenimento"),
    ("89 FM", "Mídia e Entretenimento"),
    ("Editora Abril", "Mídia e Entretenimento"),
    ("Grupo Abril", "Mídia e Entretenimento"),
    ("Editora Globo", "Mídia e Entretenimento"),
    ("Estadão", "Mídia e Entretenimento"),
    ("O Estado de S. Paulo", "Mídia e Entretenimento"),
    ("Grupo Estado", "Mídia e Entretenimento"),
    ("Folha de S.Paulo", "Mídia e Entretenimento"),
    ("Grupo Folha", "Mídia e Entretenimento"),
    ("UOL", "Mídia e Entretenimento"),
    ("Valor Econômico", "Mídia e Entretenimento"),
    ("InfoMoney", "Mídia e Entretenimento"),
    ("Exame", "Mídia e Entretenimento"),
    ("ISTOÉ", "Mídia e Entretenimento"),
    ("Veja", "Mídia e Entretenimento"),
    ("Editora Trip", "Mídia e Entretenimento"),
    ("Editora Caras", "Mídia e Entretenimento"),
    ("Editora Três", "Mídia e Entretenimento"),
    ("Editora Escala", "Mídia e Entretenimento"),
    ("Editora Alto Astral", "Mídia e Entretenimento"),
    ("Netflix Brasil", "Mídia e Entretenimento"),
    ("Netflix", "Mídia e Entretenimento"),
    ("Spotify Brasil", "Mídia e Entretenimento"),
    ("Spotify", "Mídia e Entretenimento"),
    ("Disney Brasil", "Mídia e Entretenimento"),
    ("Disney+", "Mídia e Entretenimento"),
    ("Walt Disney Brasil", "Mídia e Entretenimento"),
    ("Warner Bros Discovery", "Mídia e Entretenimento"),
    ("HBO Max", "Mídia e Entretenimento"),
    ("Paramount Brasil", "Mídia e Entretenimento"),
    ("Paramount+", "Mídia e Entretenimento"),
    ("Amazon Prime Video", "Mídia e Entretenimento"),
    ("Apple TV+", "Mídia e Entretenimento"),
    ("Telecine", "Mídia e Entretenimento"),
    ("Looke", "Mídia e Entretenimento"),
    ("Star+", "Mídia e Entretenimento"),
    ("YouTube Brasil", "Mídia e Entretenimento"),
    ("Twitch Brasil", "Mídia e Entretenimento"),
    ("TikTok Brasil", "Mídia e Entretenimento"),
    ("Kwai Brasil", "Mídia e Entretenimento"),
    ("Riot Games Brasil", "Mídia e Entretenimento"),
    ("Tencent Brasil", "Mídia e Entretenimento"),
    ("Garena", "Mídia e Entretenimento"),
    ("Ubisoft Brasil", "Mídia e Entretenimento"),
    ("Epic Games Brasil", "Mídia e Entretenimento"),
    ("Electronic Arts", "Mídia e Entretenimento"),
    ("Activision Blizzard", "Mídia e Entretenimento"),
    ("Nintendo Brasil", "Mídia e Entretenimento"),
    ("Sony PlayStation", "Mídia e Entretenimento"),
    ("PlayStation Brasil", "Mídia e Entretenimento"),
    ("Xbox Brasil", "Mídia e Entretenimento"),
    ("Cinemark", "Mídia e Entretenimento"),
    ("Cinépolis", "Mídia e Entretenimento"),
    ("Cinepolis", "Mídia e Entretenimento"),
    ("Kinoplex", "Mídia e Entretenimento"),
    ("Cinesystem", "Mídia e Entretenimento"),
    ("Moviecom", "Mídia e Entretenimento"),
    ("Live Nation Brasil", "Mídia e Entretenimento"),
    ("Time For Fun", "Mídia e Entretenimento"),
    ("T4F", "Mídia e Entretenimento"),
    ("Rock in Rio", "Mídia e Entretenimento"),

    # --- Agro e Alimentos ---
    ("JBS", "Agro e Alimentos"),
    ("Marfrig", "Agro e Alimentos"),
    ("Minerva Foods", "Agro e Alimentos"),
    ("Minerva", "Agro e Alimentos"),
    ("BRF", "Agro e Alimentos"),
    ("Seara", "Agro e Alimentos"),
    ("Sadia", "Agro e Alimentos"),
    ("Perdigão", "Agro e Alimentos"),
    ("Tyson Foods Brasil", "Agro e Alimentos"),
    ("Frimesa", "Agro e Alimentos"),
    ("Pamplona Alimentos", "Agro e Alimentos"),
    ("Frigol", "Agro e Alimentos"),
    ("Plena Alimentos", "Agro e Alimentos"),
    ("Aurora Alimentos", "Agro e Alimentos"),
    ("Aurora Coop", "Agro e Alimentos"),
    ("Coopavel", "Agro e Alimentos"),
    ("Coamo", "Agro e Alimentos"),
    ("C.Vale", "Agro e Alimentos"),
    ("Cvale", "Agro e Alimentos"),
    ("Lar Cooperativa Agroindustrial", "Agro e Alimentos"),
    ("Coopercitrus", "Agro e Alimentos"),
    ("Castrolanda", "Agro e Alimentos"),
    ("Frísia", "Agro e Alimentos"),
    ("Capal", "Agro e Alimentos"),
    ("Cotrijal", "Agro e Alimentos"),
    ("Cotribá", "Agro e Alimentos"),
    ("Cocamar", "Agro e Alimentos"),
    ("Camil Alimentos", "Agro e Alimentos"),
    ("Camil", "Agro e Alimentos"),
    ("M.Dias Branco", "Agro e Alimentos"),
    ("Dias Branco", "Agro e Alimentos"),
    ("Bunge Brasil", "Agro e Alimentos"),
    ("Bunge", "Agro e Alimentos"),
    ("Cargill Brasil", "Agro e Alimentos"),
    ("Cargill", "Agro e Alimentos"),
    ("ADM Brasil", "Agro e Alimentos"),
    ("ADM", "Agro e Alimentos"),
    ("Louis Dreyfus Company", "Agro e Alimentos"),
    ("LDC", "Agro e Alimentos"),
    ("COFCO International Brasil", "Agro e Alimentos"),
    ("Cofco", "Agro e Alimentos"),
    ("Amaggi", "Agro e Alimentos"),
    ("SLC Agrícola", "Agro e Alimentos"),
    ("SLC", "Agro e Alimentos"),
    ("Boa Safra Sementes", "Agro e Alimentos"),
    ("Boa Safra", "Agro e Alimentos"),
    ("Adecoagro", "Agro e Alimentos"),
    ("Terra Santa", "Agro e Alimentos"),
    ("BrasilAgro", "Agro e Alimentos"),
    ("Vittia", "Agro e Alimentos"),
    ("Tres Tentos", "Agro e Alimentos"),
    ("3Tentos", "Agro e Alimentos"),
    ("Kepler Weber", "Agro e Alimentos"),
    ("AGCO", "Agro e Alimentos"),
    ("John Deere", "Agro e Alimentos"),
    ("CNH Industrial", "Agro e Alimentos"),
    ("Massey Ferguson", "Agro e Alimentos"),
    ("Valtra", "Agro e Alimentos"),
    ("Stara", "Agro e Alimentos"),
    ("Jacto", "Agro e Alimentos"),
    ("Máquinas Agrícolas Jacto", "Agro e Alimentos"),
    ("Agrale", "Agro e Alimentos"),
    ("Bayer CropScience", "Agro e Alimentos"),
    ("Syngenta Brasil", "Agro e Alimentos"),
    ("Syngenta", "Agro e Alimentos"),
    ("Corteva", "Agro e Alimentos"),
    ("Corteva Agriscience", "Agro e Alimentos"),
    ("UPL", "Agro e Alimentos"),
    ("FMC Brasil", "Agro e Alimentos"),
    ("FMC Agricultural Solutions", "Agro e Alimentos"),
    ("Adama Brasil", "Agro e Alimentos"),
    ("Adama", "Agro e Alimentos"),
    ("Sumitomo Chemical", "Agro e Alimentos"),
    ("Nufarm", "Agro e Alimentos"),
    ("Albaugh", "Agro e Alimentos"),
    ("Ouro Fino Saúde Animal", "Agro e Alimentos"),
    ("Ouro Fino", "Agro e Alimentos"),
    ("Vetnil", "Agro e Alimentos"),
    ("Biotrop", "Agro e Alimentos"),
    ("Mosaic Fertilizantes", "Agro e Alimentos"),
    ("Mosaic", "Agro e Alimentos"),
    ("Yara Brasil", "Agro e Alimentos"),
    ("Yara", "Agro e Alimentos"),
    ("Heringer", "Agro e Alimentos"),
    ("Fertipar", "Agro e Alimentos"),
    ("Vale Fertilizantes", "Agro e Alimentos"),
    ("ICL Brasil", "Agro e Alimentos"),
    ("Galvani", "Agro e Alimentos"),
    ("OCP Brasil", "Agro e Alimentos"),
    ("Nestlé Brasil", "Agro e Alimentos"),
    ("Nestlé", "Agro e Alimentos"),
    ("Nestle", "Agro e Alimentos"),
    ("Danone Brasil", "Agro e Alimentos"),
    ("Danone", "Agro e Alimentos"),
    ("Mondelez Brasil", "Agro e Alimentos"),
    ("Mondelez", "Agro e Alimentos"),
    ("Mars Brasil", "Agro e Alimentos"),
    ("Mars", "Agro e Alimentos"),
    ("Ferrero Brasil", "Agro e Alimentos"),
    ("Ferrero", "Agro e Alimentos"),
    ("Kraft Heinz", "Agro e Alimentos"),
    ("Heinz", "Agro e Alimentos"),
    ("Kellogg's", "Agro e Alimentos"),
    ("Kelloggs", "Agro e Alimentos"),
    ("Lactalis Brasil", "Agro e Alimentos"),
    ("Lactalis", "Agro e Alimentos"),
    ("Itambé", "Agro e Alimentos"),
    ("Vigor", "Agro e Alimentos"),
    ("Tirol Laticínios", "Agro e Alimentos"),
    ("Piracanjuba", "Agro e Alimentos"),
    ("Embaré", "Agro e Alimentos"),
    ("Glória", "Agro e Alimentos"),
    ("Laticínios Bom Gosto", "Agro e Alimentos"),
    ("Tnuva", "Agro e Alimentos"),
    ("Yakult Brasil", "Agro e Alimentos"),
    ("Yakult", "Agro e Alimentos"),
    ("Pif Paf", "Agro e Alimentos"),
    ("Pif Paf Alimentos", "Agro e Alimentos"),
    ("Frango Sertanejo", "Agro e Alimentos"),
    ("Copacol", "Agro e Alimentos"),
    ("Vibra Agroindustrial", "Agro e Alimentos"),
    ("Catalent", "Agro e Alimentos"),
    ("Tetra Pak", "Agro e Alimentos"),
    ("Sealed Air", "Agro e Alimentos"),
    ("Cristal Pigmentos", "Agro e Alimentos"),
    ("Hypera Consumo", "Agro e Alimentos"),
    ("Diageo Brasil", "Agro e Alimentos"),
    ("Diageo", "Agro e Alimentos"),
    ("Pernod Ricard Brasil", "Agro e Alimentos"),
    ("Pernod Ricard", "Agro e Alimentos"),
    ("Bacardi Brasil", "Agro e Alimentos"),
    ("Beam Suntory", "Agro e Alimentos"),
    ("Edrington", "Agro e Alimentos"),
    ("LDC Sugar", "Agro e Alimentos"),
    ("Tereos", "Agro e Alimentos"),
    ("São Martinho", "Agro e Alimentos"),
    ("Jalles Machado", "Agro e Alimentos"),
    ("Biosev", "Agro e Alimentos"),
    ("Cocal Energia", "Agro e Alimentos"),
    ("Coruripe", "Agro e Alimentos"),
    ("Atvos", "Agro e Alimentos"),
    ("Usina Santa Terezinha", "Agro e Alimentos"),
    ("Granol", "Agro e Alimentos"),
    ("Caramuru Alimentos", "Agro e Alimentos"),
    ("Caramuru", "Agro e Alimentos"),

    # --- Serviços e Outros ---
    ("McDonalds Brasil", "Serviços e Outros"),
    ("McDonald's", "Serviços e Outros"),
    ("Arcos Dorados", "Serviços e Outros"),
    ("Burger King Brasil", "Serviços e Outros"),
    ("Burger King", "Serviços e Outros"),
    ("BK Brasil", "Serviços e Outros"),
    ("Zamp", "Serviços e Outros"),
    ("Bob's", "Serviços e Outros"),
    ("Bobs", "Serviços e Outros"),
    ("Habib's", "Serviços e Outros"),
    ("Habibs", "Serviços e Outros"),
    ("Giraffas", "Serviços e Outros"),
    ("Subway Brasil", "Serviços e Outros"),
    ("Subway", "Serviços e Outros"),
    ("Domino's Pizza", "Serviços e Outros"),
    ("Dominos", "Serviços e Outros"),
    ("Pizza Hut Brasil", "Serviços e Outros"),
    ("Pizza Hut", "Serviços e Outros"),
    ("KFC Brasil", "Serviços e Outros"),
    ("KFC", "Serviços e Outros"),
    ("Outback Brasil", "Serviços e Outros"),
    ("Outback Steakhouse", "Serviços e Outros"),
    ("Madero", "Serviços e Outros"),
    ("Bloomin Brands", "Serviços e Outros"),
    ("Spoleto", "Serviços e Outros"),
    ("Vivenda do Camarão", "Serviços e Outros"),
    ("China in Box", "Serviços e Outros"),
    ("Mr. Cheney", "Serviços e Outros"),
    ("Mr Cheney", "Serviços e Outros"),
    ("Cacau Show", "Serviços e Outros"),
    ("Chocolates Brasil Cacau", "Serviços e Outros"),
    ("Kopenhagen", "Serviços e Outros"),
    ("Chocolates Garoto", "Serviços e Outros"),
    ("Lacta", "Serviços e Outros"),
    ("Nestlé Chocolates", "Serviços e Outros"),
    ("Starbucks Brasil", "Serviços e Outros"),
    ("Starbucks", "Serviços e Outros"),
    ("Dunkin Brasil", "Serviços e Outros"),
    ("Dunkin Donuts", "Serviços e Outros"),
    ("The Coffee", "Serviços e Outros"),
    ("Casa do Pão de Queijo", "Serviços e Outros"),
    ("Sodexo Brasil", "Serviços e Outros"),
    ("Sodexo", "Serviços e Outros"),
    ("Edenred", "Serviços e Outros"),
    ("Ticket", "Serviços e Outros"),
    ("Ticket Log", "Serviços e Outros"),
    ("Alelo", "Serviços e Outros"),
    ("VR Benefícios", "Serviços e Outros"),
    ("Gympass", "Serviços e Outros"),
    ("Wellhub", "Serviços e Outros"),
    ("TotalPass", "Serviços e Outros"),
    ("Caju", "Serviços e Outros"),
    ("Flash", "Serviços e Outros"),
    ("Swile Brasil", "Serviços e Outros"),
    ("Swile", "Serviços e Outros"),
    ("ISS Brasil", "Serviços e Outros"),
    ("ISS", "Serviços e Outros"),
    ("GR Serviços", "Serviços e Outros"),
    ("Atento Brasil", "Serviços e Outros"),
    ("Atento", "Serviços e Outros"),
    ("Teleperformance Brasil", "Serviços e Outros"),
    ("Teleperformance", "Serviços e Outros"),
    ("Concentrix", "Serviços e Outros"),
    ("Webhelp", "Serviços e Outros"),
    ("Sitel", "Serviços e Outros"),
    ("Foundever", "Serviços e Outros"),
    ("AeC", "Serviços e Outros"),
    ("CSU Cardsystem", "Serviços e Outros"),
    ("Almaviva", "Serviços e Outros"),
    ("AlmavivA do Brasil", "Serviços e Outros"),
    ("Tahto", "Serviços e Outros"),
    ("Liq Corp", "Serviços e Outros"),
    ("BRQ Digital Solutions", "Serviços e Outros"),
    ("Verzani & Sandrini", "Serviços e Outros"),
    ("GPS Group", "Serviços e Outros"),
    ("Manserv", "Serviços e Outros"),
    ("Manpower", "Serviços e Outros"),
    ("ManpowerGroup", "Serviços e Outros"),
    ("Adecco Brasil", "Serviços e Outros"),
    ("Adecco", "Serviços e Outros"),
    ("Randstad Brasil", "Serviços e Outros"),
    ("Randstad", "Serviços e Outros"),
    ("Robert Half", "Serviços e Outros"),
    ("Page Personnel", "Serviços e Outros"),
    ("PageGroup", "Serviços e Outros"),
    ("Michael Page", "Serviços e Outros"),
    ("Hays Brasil", "Serviços e Outros"),
    ("Hays", "Serviços e Outros"),
    ("Robert Walters", "Serviços e Outros"),
    ("Korn Ferry", "Serviços e Outros"),
    ("Spencer Stuart", "Serviços e Outros"),
    ("Egon Zehnder", "Serviços e Outros"),
    ("Heidrick & Struggles", "Serviços e Outros"),
    ("Russell Reynolds", "Serviços e Outros"),
    ("Mercer", "Serviços e Outros"),
    ("Aon Hewitt", "Serviços e Outros"),
    ("Mckinsey", "Serviços e Outros"),
    ("McKinsey & Company", "Serviços e Outros"),
    ("BCG", "Serviços e Outros"),
    ("Boston Consulting Group", "Serviços e Outros"),
    ("Bain & Company", "Serviços e Outros"),
    ("Bain", "Serviços e Outros"),
    ("Roland Berger", "Serviços e Outros"),
    ("Oliver Wyman", "Serviços e Outros"),
    ("Strategy&", "Serviços e Outros"),
    ("AT Kearney", "Serviços e Outros"),
    ("Kearney", "Serviços e Outros"),
    ("Falconi", "Serviços e Outros"),
    ("Integration Consulting", "Serviços e Outros"),
    ("Galeazzi & Associados", "Serviços e Outros"),
    ("PRGX", "Serviços e Outros"),
    ("Protiviti", "Serviços e Outros"),
    ("ICTS Protiviti", "Serviços e Outros"),
    ("Crowe", "Serviços e Outros"),
    ("Booz Allen", "Serviços e Outros"),
    ("Bain Capital", "Serviços e Outros"),
    ("Advent International", "Serviços e Outros"),
    ("Carlyle Brasil", "Serviços e Outros"),
    ("Warburg Pincus", "Serviços e Outros"),
    ("KKR", "Serviços e Outros"),
    ("Blackstone Brasil", "Serviços e Outros"),
    ("Apollo Global Management", "Serviços e Outros"),
    ("Pátria Investimentos", "Serviços e Outros"),
]


def main():
    if not os.path.exists(LIST_PATH):
        print(f"Arquivo não encontrado: {LIST_PATH}")
        sys.exit(1)

    with open(LIST_PATH, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    from urllib.parse import urlparse

    def host_of(u: str) -> str:
        try:
            return urlparse(u).netloc.lower()
        except Exception:
            return ""

    existing_urls = {clean_url(r["URL"]).lower() for r in rows}
    existing_hosts = {host_of(r["URL"]) for r in rows if r["URL"]}
    existing_names = {r["Nome da Empresa"].strip().lower() for r in rows}

    # dedup também entradas duplicadas dentro do batch
    seen_batch_name = set()
    batch = []
    for name, seg in COMPANIES:
        k = name.strip().lower()
        if k in existing_names or k in seen_batch_name:
            continue
        seen_batch_name.add(k)
        batch.append((name, seg))

    print(f"Total candidatos a verificar: {len(batch)}")

    session = requests.Session()
    session.headers.update(HEADERS)

    today = date.today().strftime("%Y-%m-%d")
    added = 0
    results: list[tuple[str, str, str]] = []  # (name, seg, url)

    def work(item):
        name, seg = item
        try:
            url = find_url_for(name, session)
        except Exception:
            url = None
        return (name, seg, url)

    workers = int(os.environ.get("WORKERS", "20"))
    with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as ex:
        futures = {ex.submit(work, item): item for item in batch}
        done = 0
        for fut in concurrent.futures.as_completed(futures):
            done += 1
            name, seg, url = fut.result()
            if url:
                h = host_of(url)
                # Hosts compartilhados (carreiras.gupy.io, etc.) precisam de path único
                shared_hosts = {"carreiras.gupy.io", "boards.greenhouse.io",
                                "job-boards.greenhouse.io", "jobs.lever.co",
                                "jobs.kenoby.com"}
                already = (url.lower() in existing_urls or
                           (h not in shared_hosts and h in existing_hosts))
                if not already:
                    results.append((name, seg, url))
                    existing_urls.add(url.lower())
                    existing_hosts.add(h)
            if done % 50 == 0:
                print(f"  progresso {done}/{len(batch)} (+{len(results)})")

    for name, seg, url in results:
        platform = detect_platform(url)
        rows.append(
            {
                "Status da URL": "1",
                "Data de Entrada": today,
                "Nome da Empresa": name,
                "Segmento da Empresa": to_macro(seg, name),
                "Plataforma": platform,
                "URL": url,
            }
        )
        added += 1
        print(f"+ {name} -> {url}")

    with open(LIST_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDNAMES, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)

    print(f"\nAdicionadas {added} novas empresas (total {len(rows)})")


if __name__ == "__main__":
    main()
