name: 'Verify and update list'
run-name: 'Checks if the websites are up and running or not, update career-websites.csv and README.md'

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Build README.md
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update files (career-websites.csv and README.md)